Feat/#2
DaITssu/daitssu-api pull request #10
Opened 2023-07-19 07:11 UTC by swdevsw98

## Issue

- Resolves #2 

## Description

- 일정 기능에서 조회 피그마를 보면서 만들어보니 ERD에 정의 된 걸로 구현하기 어려워 새로운 엔티티를 정의했음

2023-07-21 00:48 UTC, kkanggu commented
새로 정의한 엔티티가 정확히 뭔지 알려면 ERD를 들어가는 방법 외에는 없는 상황입니다.

2023-07-21 04:25 UTC, swdevsw98 commented
erd를 제가 편집해도 되나요?

2023-07-21 14:16 UTC, kkanggu commented
> erd를 제가 편집해도 되나요?

ERD 편집이 정말 필요한가? 라고 먼저 고민해봐야 할 것 같습니다.
정말 편집이 필요하다면 혼자 뚝딱이 아니라 작업 전 미리 이슈 공유 및 방향을 정하는게 맞는 것 같습니다.

2023-07-23 04:48 UTC, swdevsw98 commented
네 저 혼자한건 잘못했네요 오늘 회의시간에 공유하겠습니다

2023-07-24 00:37 UTC, kkanggu requested changes
이후 베이스라인 확정되면 그에 맞게 수정 부탁드립니다

2023-07-24 00:37 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +    fun postCalendar(
@PostMapping은 흔히 사용하지만, 생각보다 매우 범용적으로 사용됩니다. postXXX만 봐서는 정확한 동작을 떠올리기 어려워 해당 소스를 전부 들여다보고 흐름을 파악해야 할 것 같습니다.

2023-07-24 00:37 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/controller/response/CalendarResponse.kt
> +    val dueAt: String,
날짜 계열 Type이 아닌 String에도 적용이 되나요?

2023-07-24 00:37 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/dto/AssignmentDto.kt
> +    val dueAt: LocalDateTime,
Annotation을 없앨 경우 어떠한 형식으로 값이 넘어가나요?

2023-07-24 00:37 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/repository/AssignmentRepository.kt
> +    fun findByCourseId(courseId: Long): List<Assignment>
Id는 PK로 Unique한데 List로 받아오는 이유가 있을까요?

2023-07-24 00:37 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +    }
강의가 N개라면 N개 전부 넘겨줄텐데 괜찮을까요? 그리고 아무런 조건 없이 강의 목록이 필요한 케이스가 있을까요?

2023-07-24 00:37 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        val courseResponse = CourseResponse(course.get().name)
course를 못 찾으면 불필요한 Query가 계속 날아갈텐데, 이를 미리 처리하는건 어떨까요?
그리고 Video, Assignment는 Course Entity에서 바로 가져올 수 없나요?

2023-07-24 00:37 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        }
모든 Exception 처리 목적이라면 runCathcing은 어떠실까요?

2023-07-24 00:37 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        val calendars: List<Calendar> = calendarRepository.findByDueAtBetween(startDateTime, endDateTime)
이 경우 경계값(1일 00:00:00, 말일 23:59:59)도 조회 결과에 포함이 되나요?

2023-07-24 00:37 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        }
Map을 만든 후 반복을 하는 상황인데, Map 생성 및 반복을 두 파트로 나누지 않고 한번에 처리하는 방법은 없을까요?

2023-07-24 00:37 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        val course = courseRepository.findById(courseId).get()
Course? Type이라 이렇게 하신 것 같은데, `?.` 및 `?:`을 이용하면 더 깔끔해지지 않을까요?

2023-07-24 00:37 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/entity/Course.kt
> +    private val assignments: MutableList<Assignment> = mutableListOf()
이 부분을 `(...)` 이 아닌 `{...}`에 넣은 이유가 있을까요?

2023-07-24 00:37 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        val am = Assignment(LocalDateTime.now().plusDays(7), LocalDateTime.now(), name, course)
약자로 `am`이라 쓰신 것 같은데, 소스를 처음 본다면 `am`이라는 변수명이 직관적으로 다가오지 않는 것 같습니다.

2023-07-24 02:21 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +    fun postCalendar(
명칭에 create추가했습니다!

2023-07-24 02:26 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/dto/AssignmentDto.kt
> +    val dueAt: LocalDateTime,
형식 미지정시 다음과 같이 표시 됩니다 "2023-07-16T09:30:00"

2023-07-24 02:27 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/controller/response/CalendarResponse.kt
> +    val dueAt: String,
포맷을 만들어서 넣어서 됐던거 같습니다 타입 통일했습니다!

2023-07-24 02:31 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/repository/AssignmentRepository.kt
> +    fun findByCourseId(courseId: Long): List<Assignment>
수강중인 과목의 id를 받아서 해당 과목과 관계를 가지고 있는 과제를 출력하는 함수입니다! 어떤 데이터를 주고 받는지 몰라 임시로 과목 id를 관계맺어 두었습니다. 변경사항이 있다면 추후 반영하겠습니다!

2023-07-24 02:38 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +    }
제가 피그마를 보고 유추했을 땐 유저 id나 term이 조건이 될꺼 같은데 확실치 않아서 별다른 조치를 하지 않았습니다 조건 말씀해주시면 반영해서 만들도록 하겠습니다!

2023-07-24 02:50 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        }
파싱시 에러라서 Exception을 DateTimeParseException으로 수정했습니다!

2023-07-24 02:51 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        val calendars: List<Calendar> = calendarRepository.findByDueAtBetween(startDateTime, endDateTime)
넵 포함되는거 확인했습니다!

2023-07-24 02:53 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/entity/Course.kt
> +    private val assignments: MutableList<Assignment> = mutableListOf()
수정했습니다!

2023-07-24 02:56 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        val am = Assignment(LocalDateTime.now().plusDays(7), LocalDateTime.now(), name, course)
넵 assignment로 수정했습니다!

2023-07-24 03:18 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        val courseResponse = CourseResponse(course.get().name)
수정했습니다!

2023-07-31 08:54 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        }
수정했습니다

2023-07-31 09:17 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        val course = courseRepository.findById(courseId).get()
따로 오버라이드 해서 쓴게 아니라 optional로 오는데 non-nullable이라 그런지 ?. ?:가 안되서 orElseThrow로 변경했습니다

2023-07-31 12:23 UTC, kkanggu requested changes
Baseline 확인 후 작업 부탁드립니다.

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +package com.example.test.domain.course.controller
전체 소스 common 모듈로 옮겨주시기 바랍니다. com.example 하위에 common, domain 두 패키지로 구분되어야 합니다.

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +    fun getCourseList() : List<Course> = courseService.getCourseList()
`@GetMapping` 만 이용해도 사용 가능합니다.
반환은 Response<T>로, 해당 기능에서는 Response<CourseResponse>가 될 것 같네요.

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +        courseId: Long
두 줄로 나눌 경우, 받아야 하는 값이 많아지면 가독성이 떨어질 것 같습니다.

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +    )
한 줄로 표현이 가능한데 저 부분을 세 줄로 늘린 이유가 있나요?

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +    )
`RequestCalender`는 `요청에 대한 달력` 으로 이해할 수도 있을 것 같습니다. 앞뒤 치환하는건 어떨까요?
그리고 해당 Request 값이 모두 필요하다면 값을 나눠서 넘겨줘야하는 이유가 있을까요?

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/controller/request/RequestAssignment.kt
> +    val name: String,
Swagger에서 필수값과 선택값이 구분되어서 보일텐데, prefix를 명시하는 이유가 있을까요?

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/controller/response/CalendarResponse.kt
> +class CalendarResponse (
Response<T>로 반환할 때 JSON으로 변환이 잘 되나요?

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/controller/response/CalendarResponse.kt
> +    val dueAt: LocalDateTime,
Annotation가 없다면 어떤 방식으로 출력이 되며, Timezone은 어떻게 설정이 되나요?

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/controller/response/CourseResponse.kt
> +}
값을 두 부분으로 나눠야 할 이유가 있을까요?
또한 `MutableFOOBAR`로 값을 변경할 수 있어야만 하는 이유가 있을까요?

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/controller/response/CourseResponse.kt
> +}
객체를 전부 넘겨줘서는 안 되는 상황인가요? DTO를 만들어야만 하는 이유가 있을까요?

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/dto/AssignmentDto.kt
> +    val id: Long?,
id가 null일 경우, 다른 필드에 값이 존재하는 케이스가 있나요?

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/entity/Assignment.kt
> +@Table(name = "assignment")
Postgres에는 Schema가 존재하여 이를 명시해줘야 합니다. 오히려 테이블명은 동일하다면 명시할 이유가 있나요?

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/entity/Assignment.kt
> +    val name: String,
Column의 이름은 알아서 맵핑이 되며, `?`로 Nullable을 바로 파악할 수 있을텐데 이를 명시해줘야 하나요?

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/entity/Assignment.kt
> +}
`BaseEntity` 상속하면 훨씬 깔끔할 것 같습니다.

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/entity/CalendarCourseType.kt
> +}
`달력의 강의` 로 읽히는데, 정확한 의미를 바로 파악하기 어려운 것 같습니다.
또한 해당 값이 많아질 경우 가로로 확장하면 빠른 파악이 어려울 것 같습니다.

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/repository/AssignmentRepository.kt
> +    fun findByCourseId(courseId: Long): List<Assignment>
Id로 조회한다면 `Assignment?`가 더 정확할 것 같습니다.
List<Assignment>를 원하신다면 조회 조건이 맞을까요?

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +    }
당장 조건이 명시되지 않았으나, 이를 실제로 받아서 사용하는 개발자 입장에서 생각하면 좋을 것 같습니다. 10학기에 걸쳐서 데이터가 존재할 경우 어떠한 데이터가 필요할 지 생각해보시면 개선 방향이 잡힐 것 같습니다.

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +            .orElseThrow { IllegalArgumentException("not found course") }
`findById(courseId).get() ?: throw ...` 혹은
`findByIdOrNull(courseId) ?: throw ...`는 어떨까요?

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +            .orElseThrow { IllegalArgumentException("not found course") }
현재는 Optional로 받아오지 않나요?

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +            .orElseThrow { IllegalArgumentException("not found course") }
DefaultException으로 Throw하여 Exception 통일이 더욱 좋을 것 같습니다.

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        }
FoobarRepository.findByFoo(...).map { ... } 를 이용하면 List로 바로 받아올 수 있습니다.

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        return courseResponse
현재 Response 생성부터 마무리까지 소스가 넓게 퍼져있는 상황입니다. 로직이 복잡해지면 Response 파악 과정이 더욱 어려워집니다. 미리 필요한 값들을 변수로 가져온 후, 마지막에 Response를 생성하여 바로 넘기는 방향이 유지 보수에 더욱 좋을 것 같습니다.

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        }
`2023-02-30 00:00:00` 의 경우 정상적으로 파싱이 완료되지만 해당 날짜는 존재하지 않습니다.

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/entity/CalendarCourseType.kt
> +}
enum class인데 Entity 패키지에 속하는 것이 맞나요?

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        }.toMutableMap()
```
val resultMap = calendarRepository.findByDueAtBetween(startDateTime = startDateTime, endDateTime = endDateTime).associateBy(
            { it.course }, { CalendarResponse(it.type, it.dueAt, it.name) }
        )
```

위와 같이 한줄로 표현이 가능합니다.

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        calendarRepository.save(cal)
```
val cal = Calendar(requestType, course, dateTime, name).also {
    calendarRepository.save(it)
}
```

위와 같이 두 작업을 하나로 합칠 수 있습니다.

2023-07-31 12:23 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        val vd = Video(LocalDateTime.now().plusDays(7), LocalDateTime.now(), name, course)
해당 라인만 보면 정확히 어떠한 정보가 들어가는지 알 수 없습니다. `named argument`를 이용하면 더욱 직관적으로 작성 가능합니다.

2023-08-03 04:06 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/repository/AssignmentRepository.kt
> +    fun findByCourseId(courseId: Long): List<Assignment>
네 ?로 수정하겠습니다 course랑 assignment랑 일대다 매핑이여서 courseId로 assignment 다 찾아서 리스트로 반환한게 의도였는데 다른 방식이 있나요?

2023-08-05 03:24 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +package com.example.test.domain.course.controller
수정했습니다

2023-08-05 05:12 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +    fun getCourseList() : List<Course> = courseService.getCourseList()
수정했습니다

2023-08-05 05:26 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +        courseId: Long
수정했습니다

2023-08-05 05:26 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +    )
수정했습니다

2023-08-05 05:26 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +    )
수정했습니다

2023-08-05 08:24 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/controller/request/RequestAssignment.kt
> +    val name: String,
아하 따라쳐서 별 생각없었습니다 수정했습니다

2023-08-05 08:30 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/controller/response/CalendarResponse.kt
> +class CalendarResponse (
{
    "type": "VIDEO",
    "dueAt": "2023-07-31T23:59:59",
    "name": "4주차 학습활동"
}
이렇게 됩니다

2023-08-05 08:30 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/controller/response/CalendarResponse.kt
> +    val dueAt: LocalDateTime,
어노테이션 없어도 될꺼같아서 제거했습니다

2023-08-05 08:31 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/controller/response/CourseResponse.kt
> +}
수정했습니다

2023-08-05 08:35 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/dto/AssignmentDto.kt
> +    val id: Long?,
수정했습니다

2023-08-05 08:48 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/entity/Assignment.kt
> +@Table(name = "assignment")
수정했습니다

2023-08-05 08:48 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/entity/Assignment.kt
> +    val name: String,
수정했습니다

2023-08-05 08:49 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/entity/Assignment.kt
> +}
수정했습니다

2023-08-05 08:59 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/entity/CalendarCourseType.kt
> +}
캘린더 타입으로 수정했습니다 위치는 이동시켰습니디

2023-08-05 09:10 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +            .orElseThrow { IllegalArgumentException("not found course") }
통일했습니다!
`findById(courseId).get() ?: throw ...` 다음 코드는 안되는 이유가 getOrNull이 아니여서 그런가요??
`findByIdOrNull(courseId) ?: throw ...` 해당코드로 수정했습니다

2023-08-05 09:34 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        }
잘 이해 못했는데 코드 맞는지 확인해주시면 감사하겠습니다

2023-08-05 09:35 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        return courseResponse
넵 수정했습니다

2023-08-05 09:57 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        calendarRepository.save(cal)
수정했습니다

2023-08-05 09:58 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        val vd = Video(LocalDateTime.now().plusDays(7), LocalDateTime.now(), name, course)
수정했습니다

2023-08-05 11:01 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/repository/AssignmentRepository.kt
> +    fun findByCourseId(courseId: Long): List<Assignment>
아, 제가 이해를 잘못 했네요. 현재 보이는 `List<Assignment>` 방식이 적절할 것 같습니다.

2023-08-05 11:26 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/repository/AssignmentRepository.kt
> +    fun findByCourseId(courseId: Long): List<Assignment>
또한 `List<Assignment?>` 와 같이 List 내부에 null을 허용하는게 과연 좋은 구조일까요?

2023-08-05 11:28 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +package com.example.test.domain.course.controller
이전에는 `domain/course`로 적절한 패키지 하위에 존재하였으나, 현재 `domain/main` 하위로 두 다른 도메인이 하나로 통합된 상태입니다.

2023-08-05 11:29 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +    fun getCourseList() : List<Course> = courseService.getCourseList()
요청을 보냈을 때 Response 여러개가 쌓이는 구조가 적절한 구조일까요?

2023-08-05 11:29 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +    fun getCourseList() : List<Course> = courseService.getCourseList()
기존의 Response<T>를 이용하면 좋을 것 같습니다.

2023-08-05 11:50 UTC, kkanggu requested changes
현재 작성한 코멘트와 동일하거나 비슷한 코멘트를 달아야 하는 부분은 제외하였으니 전체적으로 확인 부탁드립니다.

2023-08-05 11:50 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/controller/CourseController.kt
> +    ) : AssignmentResponse = courseService.postAssignment(assignmentRequest = requestAssignemnt)
Request 네이밍은 변경되었지만 변수명은 그대로인 것 같습니다.

2023-08-05 11:50 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/dto/response/CourseResponse.kt
> +    val assignments: List<AssignmentResponse>? = null,
값이 없다면 빈 List는 어떨까요?

2023-08-05 11:50 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/model/entity/Assignment.kt
> +    var course : Course? = null,
`@JsonIgnore`의 정확한 의도가 무엇인가요?

2023-08-05 11:50 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/service/CourseService.kt
> +        return CourseResponse(name = course.name, videos = videoResponses, assignments = assignmentResponses, term = course.term)
가로 150자? 정도가 넘어가면 좌우로 너무 길어져 한 눈에 들어오지 않습니다.
```java
val videoResponses = course.videos.map { video ->
    VideoResponse(
        id = video.id,
        name = video.name,
        dueAt = video.dueAt,
        startAt = video.startAt
    )
}
```
와 같이 작성하면 더욱 가독성이 좋을 것 같습니다.

2023-08-05 11:50 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/service/CourseService.kt
> +            .also { videoRepository.save(it) }
```java
val video = Video(LocalDateTime.now().plusDays(7), LocalDateTime.now(), videoRequest.name)
    .also { videoRepository.save(it) }
```
혹은
```java
val video = Video(LocalDateTime.now().plusDays(7), LocalDateTime.now(), videoRequest.name).also {
    videoRepository.save(it)
}
```
와 같이 also 부분을 개행 처리하면 `save`와 같은 중요한 로직을 놓칠 일이 현저히 줄어듭니다.

2023-08-05 11:50 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/service/CourseService.kt
> +            .also { videoRepository.save(it) }
또한 Video 생성 시 들어가는 값들의 의미를 파악하기 위해서는 `Video` 객체나 파라미터를 직접 확인해야 하는 상황입니다. named argument는 어떨까요?

2023-08-05 11:50 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/dto/request/AssignmentRequest.kt
> +    @Schema(description = "과제 이름입니다. ")
정말 사소하긴 하지만, Swagger 이용은 API 확인의 목적이 크지 상세 명세를 확인하는 목적이 아닙니다.
`...입니다.` 와 같은 표현이 정말 필요한가요?

2023-08-05 11:50 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/service/CourseService.kt
> +        }
기존 Java의 Lambda처럼 `FOOBAR -> FOOBAR. ...` 과 같이 명시할 수 있지만, 간단히 `it. ...` 으로도 이용이 가능합니다.
`it`에 익숙하다면 오히려 `video`, `assignment`의 네이밍으로 인하여 추가적인 정보가 있는지 파악을 시도할 수도 있습니다.

2023-08-05 11:50 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/service/CourseService.kt
> +            throw IllegalArgumentException("Invalid date format. Date should be in 'yyyy-MM-dd HH:mm:ss' format.")
`DefaultException`이 아닌 내장 Exception을 사용해야 하는 이유가 있을까요?

2023-08-05 11:50 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/service/CourseService.kt
> +        }.toMutableMap()
하나의 로직으로도 표현이 가능할 것 같은데, 두 로직으로 구분한 이유가 있을까요?

2023-08-05 11:50 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/service/CourseService.kt
> +        }.toMutableMap()
또한 Map으로 바로 가져올 수 있는 상황에서 MutableMap으로 변환하는 이유가 있을까요?

2023-08-06 01:29 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/repository/AssignmentRepository.kt
> +    fun findByCourseId(courseId: Long): List<Assignment>
수정했습니다

2023-08-06 01:30 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +package com.example.test.domain.course.controller
아 main이라 적혀있어서 그랬는데 department가 메인이였군요 변경했습니다!

2023-08-06 02:05 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +    fun getCourseList() : List<Course> = courseService.getCourseList()
수정했습니다

2023-08-06 02:08 UTC, swdevsw98 commented on common/src/main/kotlin/com/example/domain/main/controller/CourseController.kt
> +    ) : AssignmentResponse = courseService.postAssignment(assignmentRequest = requestAssignemnt)
수정했습니다

2023-08-06 02:13 UTC, swdevsw98 commented on common/src/main/kotlin/com/example/domain/main/dto/response/CourseResponse.kt
> +    val assignments: List<AssignmentResponse>? = null,
수정했습니다

2023-08-06 02:14 UTC, swdevsw98 commented on common/src/main/kotlin/com/example/domain/main/model/entity/Assignment.kt
> +    var course : Course? = null,
이전에 매핑에서 무한루프가 안생겼는데 베이스라인 바꾸고 이번에 갑자기 생기더라구요 혹시 해결방법이 있을까요??

2023-08-06 02:15 UTC, swdevsw98 commented on common/src/main/kotlin/com/example/domain/main/model/entity/Assignment.kt
> +    var course : Course? = null,
또 RequestLoggingFilter가 body를 뺏어가서 포스트맨이 안되는 일도 있어서 일단 주석처리하고 진행하긴 했는데 이것도 방법 알려주시면 수정하겠습니다

2023-08-06 02:18 UTC, swdevsw98 commented on common/src/main/kotlin/com/example/domain/main/service/CourseService.kt
> +        return CourseResponse(name = course.name, videos = videoResponses, assignments = assignmentResponses, term = course.term)
수정했습니다

2023-08-06 02:20 UTC, swdevsw98 commented on common/src/main/kotlin/com/example/domain/main/service/CourseService.kt
> +            .also { videoRepository.save(it) }
현재 코드가 위와 일치하는거 같은데 아래 코드로 변경할까요?

2023-08-06 02:21 UTC, swdevsw98 commented on common/src/main/kotlin/com/example/domain/main/dto/request/AssignmentRequest.kt
> +    @Schema(description = "과제 이름입니다. ")
제거했습니다

2023-08-06 02:28 UTC, swdevsw98 commented on common/src/main/kotlin/com/example/domain/main/service/CourseService.kt
> +        }
넵 it이 아직 안익숙하네요 수정했습니다!

2023-08-06 02:35 UTC, swdevsw98 commented on common/src/main/kotlin/com/example/domain/main/service/CourseService.kt
> +            throw IllegalArgumentException("Invalid date format. Date should be in 'yyyy-MM-dd HH:mm:ss' format.")
날짜 유효성하면서 진행할려고 했는데 먼저 했습니다!

2023-08-06 02:42 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        }.toMutableMap()
List로 반환해야해서 groupby로 수정했습니다

2023-08-06 02:43 UTC, swdevsw98 commented on common/src/main/kotlin/com/example/domain/main/service/CourseService.kt
> +        }.toMutableMap()
수정했습니다

2023-08-06 04:24 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +    fun getCourseList() : List<Course> = courseService.getCourseList()
다른 Controller도 동일한 방식으로 수정 부탁드립니다!

2023-08-06 04:27 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/dto/response/CourseResponse.kt
> +    val assignments: List<AssignmentResponse>? = null,
emptyList로 처리한다면 List<T>? 와 같이 null을 허용할 필요가 있을까요?

2023-08-06 04:29 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/model/entity/Assignment.kt
> +    var course : Course? = null,
음, 재현을 위해서 더욱 자세한 정보가 필요할 것 같습니다.
해당 이슈와 사용한 Request 정보(Postman 혹은 Curl)를 간단히 정리해서 별도 Issue로 올려주시면 좋을 것 같습니다.

2023-08-06 04:31 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/service/CourseService.kt
> +            .also { videoRepository.save(it) }
also 부분 개행 덕분에 가독성은 더욱 좋아졌습니다. 다만
```java
val video = Video(
    dueAt = LocalDateTime.now().plusDays(7),
    startAt = LocalDateTime.now(),
    name = videoRequest.name,
    course = course
)
    .also { videoRepository.save(it) }
```
와 같이 코틀린 자체적인 Indent로 인하여 두 구문이 조금 떨어진 느낌이 듭니다.
```java
val video = Video(
    dueAt = LocalDateTime.now().plusDays(7),
    startAt = LocalDateTime.now(),
    name = videoRequest.name,
    course = course
).also { videoRepository.save(it) }
```
위처럼 작성하면 더욱 간결하고 좋을 것 같습니다.

2023-08-06 04:32 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        }
혹시 parse하면 자동으로 마지막날로 보정해버리고 에러를 안내고, LocalDateTime으로 받아오면 exceptionHandler에서 처리 해주는데  
BaseException에 들어있지 않은 에러면 어떻게 처리 해줘야하나요??

2023-08-06 04:37 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +    fun getCourseList() : List<Course> = courseService.getCourseList()
수정했습니다!

2023-08-06 04:40 UTC, swdevsw98 commented on common/src/main/kotlin/com/example/domain/main/service/CourseService.kt
> +            .also { videoRepository.save(it) }
수정했습니다!

2023-08-06 04:44 UTC, swdevsw98 commented on common/src/main/kotlin/com/example/domain/main/dto/response/CourseResponse.kt
> +    val assignments: List<AssignmentResponse>? = null,
수정했습니다!

2023-08-06 04:49 UTC, swdevsw98 commented on common/src/main/kotlin/com/example/domain/main/model/entity/Assignment.kt
> +    var course : Course? = null,
갑자기 제거하고 하니까 됐습니다.. 제거하겠습니다! RequestLoggingFilter 문제는 한번 봐주시면 감사하겠습니다

2023-08-06 06:54 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        }
음... 정확히 어떤 질문인지 이해를 못했습니다.
1. parse할 경우 자동으로 마지막날로 보정되지 않습니다. 보정이 된다면 02-30과 같은 날짜가 나올 수 없습니다.
2. 현재 모든 예외를 ExceptionHandler에서 처리하도록 하였습니다.
3. BaseException에 들어있지 않는 예외는 Unexpected Exception으로, 자동으로 `code = 1`로 설정합니다. Response는 정상적으로 보이지만, 이러한 Response 자체가 발생하는 것이 안 좋습니다.

2023-08-06 07:52 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        }
1. 현재 코드로 진행시 dueAt을 String으로 받아와서 포맷으로 파싱했는데 입력을 `"dueAt" : "2023-02-30 23:59:59"` 이렇게 주면 저장 되는게  `"dueAt": "2023-02-28T23:59:59"` 자동으로 보정 되서 파싱이 됩니다. 

2. 그래서 그 이후 dueAt을 LocalDateTime으로 변경해서 진행하였습니다. 
- 잘못된 포맷으로 전달("dueAt" : "2023-02-3023:59:59")
- 잘못된 값으로 전달 ("dueAt" : "2023-02-30 23:59:59")
둘다 같은 DateTimeParseException이 발생하는데 이는 BaseException에 존재하지 않아 else문으로 빠집니다!

요약하자면
1. String -> LocalDateTime으로 파싱하면 자동으로 마지막날로 변경되어 따로 valid 함수를 만들어서 유효성 검사를 실시할 수 없음
2. LocalDateTime으로 처음부터 받으니 ExceptionHandler가 처리해주는데 else문장으로 빠져서 어떻게 처리해야할지 모르겠음

어떻게 수정하는게 좋을까요??

2023-08-06 11:11 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        }
분명 한달전에 `yyyy-MM-dd` 문제 발견했었는데, 집에서는 재현이 안 되는 상황이네요. 해당 문제는 다시 확인해보고 이슈가 될 것 같으면 추가로 코멘트 남기겠습니다.

처음부터 2번처럼 받기보다는, 직접 String -> LocalDateTime으로 변환이 나을 것 같습니다. 날짜 불일치 문제라면 LocalDateTime -> String 변환하여 두 String이 동일한지 비교하는 방식도 있습니다.

2023-08-06 11:15 UTC, kkanggu approved these changes
고생하셨습니다. Merge 관련된 내용은 회의에서 한번 언급 드리겠습니다.

2023-08-06 11:15 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/course/controller/CourseController.kt
> +        Response(data = courseService.getCalendar(dateRequest = date))
현재 방식 자체는 전혀 문제가 되지 않습니다. 한가지 아쉬운 점은 Map + List가 섞인 형태라 전체 데이터 파악을 하기 위해서는 별도의 작업이 필요할 수 있습니다. 당장 필요한 상황은 아니나, 전체 Key와 Value의 개수 등에 대한 정보를 field로 넣어주는 것도 좋을 것 같습니다.

2023-08-10 08:43 UTC, closed without merging