[#61] user_id 추가 및 일정에서 user 핸들링하기
DaITssu/daitssu-api pull request #107
Opened 2024-01-04 05:32 UTC by swdevsw98

## Issue

- Resolves #61 

## Description

- userId 추가해서 calendar 핸들링
- Todo 반영
- coflict 해결

## Check List

- [ ]  PR 제목을 커밋 규칙에 맞게 작성
- [ ]  PR에 해당되는 Issue를 연결 완료
- [ ]  적절한 라벨 설정
- [ ]  작업한 사람 모두를 Assign
- [ ]  작업한 팀에게 Code Review 요청 (Reviewer 등록)
- [ ]  `main` 브랜치의 최신 상태를 반영하고 있는지 확인

## Screenshot

2024-01-07 14:36 UTC, kkanggu requested changes

2024-01-07 14:36 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
> +        }
변수 선언 없이 바로 `.map`을 이어 return이 가능합니다. 현재 변수를 따로 빼는데, 메리트가 없어보입니다.

2024-01-07 14:36 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
> +            ?: throw DefaultException(ErrorCode.COURSE_NOT_FOUND)
강의가 DB의 id나 강의 고유 번호 등으로 들어오지 않는 것일까요? 같은 이름의 강의가 여러 학기에 걸쳐 존재할 가능성이 높습니다.

2024-01-09 12:59 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
> +        }
수정했습니다!

2024-01-09 13:12 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
> +            ?: throw DefaultException(ErrorCode.COURSE_NOT_FOUND)
피그마에 분류가 한글이라서 그렇게 생각했던거 같습니다! 수정했습니다!

2024-01-15 12:15 UTC, kkanggu approved these changes

2024-01-15 12:23 UTC, merged