[#6] 커뮤니티 게시글 생성 및 조회 API
DaITssu/daitssu-api pull request #17
Opened 2023-08-05 06:37 UTC by CreatePath

## Issue

- Resolves #6 

## Description

- 커뮤니티 게시글 생성 및 조회에 필요한 Entity, Repository 작성
- 커뮤니티 Service, Controller 작성
- 게시글 생성 요청을 받을 request dto 작성
- 게시글 생성/조회 요청의 응답을 저장하는 response dto 작성
- 추후 구현할 좋아요 기능에 필요한 Reaction entity, Repository 작성
- 게시글 생성/조회 test code 작성

## Check List

- [ ]  PR 제목을 커밋 규칙에 맞게 작성
- [ ]  PR에 해당되는 Issue를 연결 완료
- [ ]  적절한 라벨 설정
- [ ]  작업한 사람 모두를 Assign
- [ ]  작업한 팀에게 Code Review 요청 (Reviewer 등록)
- [ ]  `main` 브랜치의 최신 상태를 반영하고 있는지 확인

2023-08-05 07:04 UTC, kkanggu requested changes
궁금하신점은 편하게 문의 주셔도 됩니다.

2023-08-05 07:04 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/controller/CommunityController.kt
> +    @PostMapping("/write")
community 라는 경로이지만 Article이 메인인가? 느낌이 드네요. 위 Path는 여러 개념이 섞인 것 같습니다.

2023-08-05 07:04 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/controller/CommunityController.kt
> +    @PostMapping("/write")
++ Post에 `.../wrtie` 라는 경로를 이용하는데, Rest에 적절한 Path일까요?

2023-08-05 07:04 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/controller/CommunityController.kt
> +        = Response(data = communityService.getArticle(id))
위 Path가 모호한 상황이기에 `id`라는 변수명도 Community의 id로 인식될 가능성이 있을 것 같습니다.

2023-08-05 07:04 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/dto/response/ArticleResponse.kt
> +    val updatedAt: LocalDateTime,
생성 시각과 갱신 시각을 모두 넘겨줘야 하는 상황인가요?

2023-08-05 07:04 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/model/entity/Article.kt
> +    @JoinColumn(name = "user_id")
`?`가 없어서 Null이 될 수 없는데, `@NotNull`이 필요한가요?

2023-08-05 07:04 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/model/entity/Article.kt
> +    var imageUrl: String? = null,
기본적으로 `imageUrl` -> `image_url`이 되는데, column 명시가 필요한 상황인가요?

2023-08-05 07:04 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/model/entity/Reaction.kt
> +    val user: User,
두 Entity의 Eager Loading이 일어나는데, 의도하신 동작인가요?

2023-08-05 07:04 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/service/CommunityService.kt
> +            createdAt = article.createdAt, updatedAt = article.updatedAt)
named argument를 이용하더라도 이렇게 많아지면 하나씩 개행해주는게 더 가독성에 좋지 않을까요?

2023-08-05 07:04 UTC, kkanggu commented on common/src/test/kotlin/com/example/domain/main/service/CommunityServiceTest.kt
> +            ?: throw Error()
when을 검증해야 하는데, given에서 예외를 발생하는게 좋은 테스트일까요?

2023-08-05 09:53 UTC, CreatePath commented on common/src/main/kotlin/com/example/domain/main/controller/CommunityController.kt
> +    @PostMapping("/write")
15번째 줄은 커뮤니티를 구현한다는 생각에 path를 광범위하게 잡았던 것 같습니다.
community -> community/article 로 수정하겠습니다.

post요청의 url에 wrtie를 추가적으로 붙일 필요는 없겠네요.
그럼 PostMapping 경로는 따로 지정하지 않는 것이 좋을까요??

2023-08-05 09:58 UTC, CreatePath commented on common/src/main/kotlin/com/example/domain/main/dto/response/ArticleResponse.kt
> +    val updatedAt: LocalDateTime,
figma에서 게시글 조회 페이지를 보니 해당 게시글이 작성된 시각 정보가 있어서 추가했습니다.
아마 갱신 시각만 사용할 것 같으니 갱신 시각만 넘겨주는 걸로 하겠습니다.

2023-08-05 09:59 UTC, CreatePath commented on common/src/main/kotlin/com/example/domain/main/model/entity/Article.kt
> +    @JoinColumn(name = "user_id")
앗 @NotNull 지우겠습니다!

2023-08-05 10:01 UTC, CreatePath commented on common/src/main/kotlin/com/example/domain/main/model/entity/Article.kt
> +    var imageUrl: String? = null,
이건 제가 column 이름이 어떻게 바뀌는지 잘 몰라서 쓴 것 같습니다...
name 지우도록 하겠습니다.

2023-08-05 10:09 UTC, CreatePath commented on common/src/main/kotlin/com/example/domain/main/model/entity/Reaction.kt
> +    val user: User,
아 Lazy Loading으로 수정하겠습니다.

2023-08-05 10:09 UTC, CreatePath commented on common/src/main/kotlin/com/example/domain/main/service/CommunityService.kt
> +            createdAt = article.createdAt, updatedAt = article.updatedAt)
넵 수정하겠습니다!

2023-08-05 10:59 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/controller/CommunityController.kt
> +    @PostMapping("/write")
상황에 따라 다르지만, 보통 `.../write`와 같이 동사 형태의 Path는 찾아보기 어렵습니다.
그러한 방식으로 진행하고자 하시면 [Google API Guide](https://cloud.google.com/apis/design/custom_methods?hl=ko) 방식이 더욱 적절할 것 같습니다.

2023-08-05 15:11 UTC, CreatePath commented on common/src/test/kotlin/com/example/domain/main/service/CommunityServiceTest.kt
> +            ?: throw Error()
음... 좋은 방법이 안 떠오르는데, Mockk를 이용해서 가짜 repository 객체를 사용하는 방식으로 테스트 코드를 짜야할까요?

2023-08-06 04:22 UTC, kkanggu commented on common/src/test/kotlin/com/example/domain/main/service/CommunityServiceTest.kt
> +            ?: throw Error()
간단하게 생각하시면 됩니다. `@BeforeXXX` 이용하여 미리 테스트용 데이터를 저장하였으니, 바로 꺼내서 사용하면 됩니다.
```java
val user = userRepository.findByStudentId(20221111)
```
혹은
```java
val user = userRepository.findAll()[0]
```
처럼 이용해도 될 것 같습니다.

2023-08-06 06:47 UTC, CreatePath commented on common/src/test/kotlin/com/example/domain/main/service/CommunityServiceTest.kt
> +            ?: throw Error()
`findAll`을 이용하는 방식으로 수정하겠습니다.

2023-08-06 06:57 UTC, CreatePath commented
리뷰에서 말씀해주신 것들 반영했습니다. 확인해주세요!

2023-08-06 07:49 UTC, kkanggu approved these changes
고생하셨습니다.

2023-08-09 08:39 UTC, kkanggu requested changes
ControllerTest 때문에 승인은 하지 않았습니다. 다른 두 코멘트는 당장 큰 이슈는 없어보입니다.

2023-08-09 08:39 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/enums/Topic.kt
> +    }
단순 Iteration으로 찾는 방식은 어떨까요? 성능을 최대한 끌어내야 하는 상황이 아닌데, 이렇게까지 성능 관리를 해야하나? 라는 생각이 드네요.

2023-08-09 08:39 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/service/ArticleService.kt
> +            writerNickName = user.nickname!!,
Null -> NotNull로 처리하는 정확한 이유가 뭔가요? Entity에서는 Nullable인데, Response에서는 NotNull이라 혼동이 올 수도 있을 것 같습니다.

2023-08-09 08:39 UTC, kkanggu commented on common/src/test/kotlin/com/example/domain/main/controller/ArticleControllerTest.kt
> +        val articleResponse: Response<ArticleResponse> = articleController.getArticle(savedArticle.id)
이러한 Controller 호출 방식은 항상 정확한 요청이 들어와 해당 메소드가 호출되는 흐름인데요. 요청 자체를 검증하려면 이러한 방식이 맞을까요?

2023-08-09 14:24 UTC, CreatePath commented on common/src/main/kotlin/com/example/domain/main/service/ArticleService.kt
> +            writerNickName = user.nickname!!,
작성자 닉네임이 없으면 글 작성이 안되기 때문에 NotNull로 처리했습니다.
아 그러면 닉네임이 null일 경우에 예외 처리를 해야겠네요. 수정하겠습니다.

2023-08-09 14:27 UTC, CreatePath commented on common/src/main/kotlin/com/example/domain/main/enums/Topic.kt
> +    }
너무 과했나보군요... 다음부턴 성능 관리가 얼마나 필요한지도 고려하며 코드 작성하도록 하겠습니다.

2023-08-09 14:34 UTC, CreatePath commented on common/src/test/kotlin/com/example/domain/main/controller/ArticleControllerTest.kt
> +        val articleResponse: Response<ArticleResponse> = articleController.getArticle(savedArticle.id)
아 controller는 http 요청을 잘 처리하는지 체크해야겠네요.
MockMvc를 이용해서 http 요청을 날리고 응답을 체크하는 방식으로 수정하겠습니다.

2023-08-10 16:01 UTC, kkanggu requested changes
기존에 Unresolved 된 항목들도 확인 부탁드립니다.

2023-08-10 16:01 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/dto/request/ArticlePostRequest.kt
> +    val nickname: String?
Body에 nickname 값이 아예 없으면 어떻게 되나요?

2023-08-10 16:01 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/service/ArticleService.kt
> +            ?: throw DefaultException(ErrorCode.BAD_REQUEST, HttpStatus.NOT_FOUND)
Status Code만 보면 404가 적절하지만, Custom Code 이용 시 일반적으로 Status Code 보다는 Body를 주로 보기에 404로 넘겨주는게 필수적인건 아닙니다.

2023-08-10 16:01 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/dto/request/ArticlePostRequest.kt
>      val topic: String,
Enum으로 바로 받아올 수 있는데, String으로 받아서 Enum으로 변환하는 과정이 필요한가요?

2023-08-10 16:01 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/service/ArticleService.kt
> +            throw DefaultException(ErrorCode.BAD_REQUEST, HttpStatus.BAD_REQUEST)
기본 Status Code가 `BAD_REQUEST`인데 이를 명시할 필요가 있나요?

2023-08-10 16:01 UTC, kkanggu commented on common/src/test/kotlin/com/example/domain/main/controller/ArticleControllerTest.kt
> +            .andDo(MockMvcResultHandlers.print())
print를 진행하는 이유는 뭔가요?

2023-08-10 16:15 UTC, CreatePath commented on common/src/main/kotlin/com/example/domain/main/dto/request/ArticlePostRequest.kt
> +    val nickname: String?
null 값을 기본 값으로 갖도록 수정하겠습니다

2023-08-10 16:15 UTC, CreatePath commented on common/src/main/kotlin/com/example/domain/main/service/ArticleService.kt
> +            ?: throw DefaultException(ErrorCode.BAD_REQUEST, HttpStatus.NOT_FOUND)
status code 지우도록 하겠습니다

2023-08-10 16:16 UTC, CreatePath commented on common/src/main/kotlin/com/example/domain/main/dto/request/ArticlePostRequest.kt
>      val topic: String,
request dto에서 enum 타입을 받아오는 방법을 몰라서 저렇게 짰는데, Enum으로 바로 받아오도록 수정하겠습니다.

2023-08-10 16:16 UTC, CreatePath commented on common/src/main/kotlin/com/example/domain/main/service/ArticleService.kt
> +            throw DefaultException(ErrorCode.BAD_REQUEST, HttpStatus.BAD_REQUEST)
http status code 지우겠습니다

2023-08-10 16:16 UTC, CreatePath commented on common/src/test/kotlin/com/example/domain/main/controller/ArticleControllerTest.kt
> +            .andDo(MockMvcResultHandlers.print())
body 내용이 어떻게 들어갔는지 확인하기 위해서 넣은 건데, 필요하진 않으니 지우도록 하겠습니다.

2023-08-10 17:18 UTC, CreatePath commented on common/src/main/kotlin/com/example/domain/main/dto/request/ArticlePostRequest.kt
>      val topic: String,
혹시 Enum으로 바로 받아온다는 말씀이 프론트에서 "topic": "잡담" 이 아니라 "topic": "CHAT"으로 받아온다는 의미인가요??

2023-08-11 00:31 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/dto/request/ArticlePostRequest.kt
>      val topic: String,
네 맞습니다. 사실상 Enum으로 관리하는 데이터를 한글로 받아와서 처리해야한다는게 굳이? 라는 느낌이 강하게 드네요

2023-08-12 06:50 UTC, CreatePath commented on common/src/main/kotlin/com/example/domain/main/enums/Topic.kt
> +    }
DTO에서 String이 아니라 Topic으로 받도록 수정하고 보니 String -> Topic 변환할 필요가 없어져서 이 부분은 삭제했습니다.

2023-08-12 06:51 UTC, CreatePath commented on common/src/main/kotlin/com/example/domain/main/controller/CommunityController.kt
> +        = Response(data = communityService.getArticle(id))
`id` -> `articleId`로 수정했습니다.

2023-08-12 08:32 UTC, kkanggu requested changes
Swagger 적용까지 부탁드립니다.

2023-08-12 08:32 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/dto/request/ArticlePostRequest.kt
> +data class ArticlePostRequest(
HTTP Method로 인해 Post를 이용하신 것 같으나, 이 때문에 오히려 혼동이 옵니다. 네이밍만 보면 Article을 어딘가로 전송하거나 게시한다고 생각이 드네요.

2023-08-12 08:32 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/service/ArticleService.kt
> +        }
여기서 해당 예외가 발생하면 이를 호출한 측에서는 어떤 이유로 처리에 실패했는지 알 수 없습니다. ErrorCode 내부에서 적절한거 새로 만드는게 나을 것 같습니다.

2023-08-12 16:02 UTC, CreatePath commented on common/src/main/kotlin/com/example/domain/main/dto/request/ArticlePostRequest.kt
> +data class ArticlePostRequest(
`ArticleWritingRequest`로 수정하겠습니다.

2023-08-12 16:04 UTC, CreatePath commented on common/src/main/kotlin/com/example/domain/main/service/ArticleService.kt
> +        }
넵 에러 코드 추가하겠습니다.

2023-08-13 02:31 UTC, kkanggu commented on common/src/main/kotlin/com/example/domain/main/dto/request/ArticlePostRequest.kt
> +data class ArticlePostRequest(
보통 일반 동사(`write`)를 이용하기에, `Writing` 보다는 `Write`가 나을 것 같습니다.

2023-08-13 12:24 UTC, CreatePath commented on common/src/main/kotlin/com/example/domain/main/dto/request/ArticlePostRequest.kt
> +data class ArticlePostRequest(
넵 수정하겠습니다.

2023-08-17 11:12 UTC, closed without merging