Feat/notice fs
DaITssu/daitssu-api pull request #41
Opened 2023-08-28 12:58 UTC by JooHui-void

## Issue

- Resolves #5 ]

## Description

- 공지사항 카테고리별 필터링 및 상세 페이지 api 구현 

## Check List

- [ ]  PR 제목을 커밋 규칙에 맞게 작성
- [ ]  PR에 해당되는 Issue를 연결 완료
- [ ]  적절한 라벨 설정
- [ ]  작업한 사람 모두를 Assign
- [ ]  작업한 팀에게 Code Review 요청 (Reviewer 등록)
- [ ]  `main` 브랜치의 최신 상태를 반영하고 있는지 확인

## Screenshot

2023-08-28 13:12 UTC, kkanggu requested changes
중복되는 부분은 적지 않았습니다.

2023-08-28 13:12 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/notice/controller/NoticeController.kt
> +@TestPropertySource("classpath:/application-local.yml")
이게 꼭 필요한가요?

2023-08-28 13:12 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/notice/dto/ResponseDTO.kt
> +)
해당 DTO 사용하는 곳이 없지 않나요?

2023-08-28 13:12 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/notice/model/entity/FunSystem.kt
> +)
기존 컨벤션 적용 및 테이블 스키마 확인하시기 바랍니다.

2023-08-28 13:12 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/notice/controller/NoticeController.kt
> +        @PathVariable category: String
Enum으로 관리하지 않아도 괜찮나요?

2023-08-28 13:12 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/notice/service/NoticeService.kt
> +        }
실제로 category 값이 한글 `전체` 로 들어오나요?

2023-08-28 13:12 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/notice/service/NoticeService.kt
> +        }
return 구문이 두개라 가독성이 떨어지는 것 같습니다.

2023-08-28 13:12 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/notice/service/NoticeService.kt
> +        return NoticeResponse.fromNotice(notice)
기존 컨벤션 확인하시고 예외 처리 하시면 될 것 같습니다.

2023-08-28 13:12 UTC, kkanggu commented on src/test/kotlin/com/example/daitssuapi/domain/notice/H2DatabaseTest.kt
> +}
develop에서 해당 부분 해결하였기에 본 Util 필요성이 느껴지지 않습니다.

2023-08-28 13:12 UTC, kkanggu commented on src/test/kotlin/com/example/daitssuapi/domain/notice/NoticeControllerTest.kt
> +@MockBean(JpaMetamodelMappingContext::class)
사용하는 목적이 뭘까요?

2023-08-28 13:12 UTC, kkanggu commented on src/test/kotlin/com/example/daitssuapi/domain/notice/NoticeControllerTest.kt
> +        println(result.response.contentAsString)
테스트에서 값 검증이 필요하면 assert*로 검증하는게 더 낫지 않을까요? 이상한 값으로 넘어와도 테스트 돌리는 것으로는 판별이 불가능할 것 같습니다.

2023-09-01 08:06 UTC, JooHui-void commented on src/main/kotlin/com/example/daitssuapi/domain/notice/dto/ResponseDTO.kt
> +)
commom DTO 발견하기전에 만든게 들어갔네요... 반영하겠습니다!

2023-09-01 08:12 UTC, JooHui-void commented on src/main/kotlin/com/example/daitssuapi/domain/notice/model/entity/FunSystem.kt
> +)
테이블 스키마에서 category 부분을 제 생각대로 임의 추가를 했는데 notice_fs 테이블에도 필요한게 아닌가 궁금합니다..! 제가 테이블 구조를 잘못 이해하고 있을수도 있습니다
![image](https://github.com/DaITssu/daitssu-api/assets/69834729/c395e862-1da7-4913-91af-a6b033dd3a9e)

2023-09-01 08:15 UTC, JooHui-void commented on src/main/kotlin/com/example/daitssuapi/domain/notice/controller/NoticeController.kt
> +        @PathVariable category: String
위의 펀시스템 코멘트까지 확인되면 만들도록 하겠습니다..!

2023-09-01 08:19 UTC, JooHui-void commented on src/test/kotlin/com/example/daitssuapi/domain/notice/H2DatabaseTest.kt
> +}
넵 반영하겠습니다!

2023-09-01 08:22 UTC, JooHui-void commented on src/main/kotlin/com/example/daitssuapi/domain/notice/service/NoticeService.kt
> +        }
카테고리 이름이 전체이기는 한데 들어오는건 프론트에서 어떻게 처리할지 몰라서 일단 카테고리 이름으로 따라갔습니다..! 혹시 편하거나 좋은 방법이 있을까요

2023-09-01 08:35 UTC, JooHui-void commented on src/test/kotlin/com/example/daitssuapi/domain/notice/NoticeControllerTest.kt
> +        println(result.response.contentAsString)
아하 감사합니다!

2023-09-01 09:38 UTC, JooHui-void commented on src/test/kotlin/com/example/daitssuapi/domain/notice/NoticeControllerTest.kt
> +@MockBean(JpaMetamodelMappingContext::class)
저도 테스팅은 잘 몰라서 이리저리 추가했는데 찾아보니 둘중 하나만 사용하면 되는 것 같아요 AutoConfigureMockMvc만 남기고 MockBean 어노테이션은 제거하도록 하겠습니다

2023-09-02 08:30 UTC, JooHui-void commented on src/main/kotlin/com/example/daitssuapi/domain/notice/controller/NoticeController.kt
> +@TestPropertySource("classpath:/application-local.yml")
TestPropertySource 어노테이션 제거했습니다..!

2023-09-04 00:08 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/notice/model/entity/FunSystem.kt
> +)
ERD가 완전하지 않기에 변경 제안 편하게 하셔도 됩니다.
ERD 변경 사항은 따로 이슈에 정리해주시고, 이슈가 없어보이면 바로 반영 가능합니다.

2023-09-04 00:12 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/notice/service/NoticeService.kt
> +        }
변동이 적고 개수도 적은 데이터이기에 일반적으로 Enum으로 관리할 가능성이 높습니다. 각 Enum 값에 추가적인 필드로 한글명까지 적으면 유지보수에도 용이할 것 같습니다.

2023-09-04 00:36 UTC, kkanggu approved these changes
머지 후에도 잘 작동하는지 확인 부탁드립니다. 고생하셨습니다.

2023-09-04 00:36 UTC, kkanggu commented on src/test/kotlin/com/example/daitssuapi/domain/notice/NoticeControllerTest.kt
> +                    "\"updatedAt\":\"0999-12-27T00:32:08\"}]}")
순수 Text 검증이라 의도한 데이터가 직관적으로 읽히지 않으며, 변경에 민감하게 반응할 것 같습니다. jsonPath나 jsonObjectMapper 등을 이용하면 좋을 것 같습니다.

2023-09-04 19:20 UTC, JooHui-void commented on src/test/kotlin/com/example/daitssuapi/domain/notice/NoticeControllerTest.kt
> +                    "\"updatedAt\":\"0999-12-27T00:32:08\"}]}")
확인했습니다!

2023-09-12 13:38 UTC, kkanggu requested changes

2023-09-12 13:38 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/notice/controller/NoticeController.kt
> +        Response(data = noticeService.getNoticeList(category))
Enum 타입이 있는데 String으로 받아야 할 이유가 있을까요?

2023-09-12 13:38 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/notice/model/entity/Notice.kt
> +    var category: NoticeCategory?,
카테고리 없이 저장해야할 이유가 있나요?

2023-09-12 13:38 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/notice/service/NoticeService.kt
> +            }
다른 수정 사항에 따라 변경되어야 하지만, 해당 소스만 놓고 보면 아래 방식이 더욱 좋을 것 같습니다.

```kotlin
notices = NoticeCategory.fromCode(category)?.let {
    noticeRepository.findByCategory(it)
} ?: throw DefaultException(errorCode = ErrorCode.INVALID_CATEGORY)
```

2023-09-12 13:38 UTC, kkanggu commented on src/test/kotlin/com/example/daitssuapi/domain/notice/NoticeControllerTest.kt
> +        val result = mockMvc.get("/notice/전체")
한글로 요청하기보다는, Enum값 그대로 이용한 `/notice/ALL` 이 더욱 좋을 것 같습니다.

2023-09-17 15:57 UTC, JooHui-void commented on src/test/kotlin/com/example/daitssuapi/domain/notice/NoticeControllerTest.kt
> +        val result = mockMvc.get("/notice/전체")
수정하겠습니다!

2023-09-17 15:59 UTC, JooHui-void commented on src/main/kotlin/com/example/daitssuapi/domain/notice/service/NoticeService.kt
> +            }
알려주셔서 감사해요 반영해두겠습니다!

2023-09-17 16:17 UTC, JooHui-void commented on src/main/kotlin/com/example/daitssuapi/domain/notice/controller/NoticeController.kt
> +        Response(data = noticeService.getNoticeList(category))
맞지 않은 enum 처리를 service레이어에서 처리하기 위해 일단 컨트롤러에서는 string으로 넘기기만 했습니다..! 저 위치에서 enum으로 받는게 가능한가요?!

2023-09-18 12:08 UTC, HwanGonJang reviewed
🙌

2023-09-18 12:08 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/notice/controller/FunSystemController.kt
> +        Response(data = funSystemService.getFunSystemList(category))
<img width="313" alt="image" src="https://github.com/DaITssu/daitssu-api/assets/33739448/6a87b578-1bdb-45f7-b7a0-e3ac3a22a935"> 
 
전체 조회는 이렇게 리스트 뷰라 데이터가 큰 내용 같은애들은 같이 안줘도 좋을 것 같아요.
따로 Response 만들어서 id, title, category, createdAt 정도만 반환해주면 좋을 것 같아요!

2023-09-18 12:08 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/notice/controller/FunSystemController.kt
> +        Response(data = funSystemService.getFunSystemList(category))
아래 Notice도 마찬가지!

2023-09-18 13:15 UTC, kkanggu approved these changes

2023-09-18 17:56 UTC, JooHui-void commented on src/main/kotlin/com/example/daitssuapi/domain/notice/controller/FunSystemController.kt
> +        Response(data = funSystemService.getFunSystemList(category))
넵 수정해두겠습니다..!

2023-09-18 17:57 UTC, merged