Feature/로그인 로직 구현
DaITssu/daitssu-api pull request #42
Opened 2023-08-30 14:52 UTC by HwanGonJang

## Issue

- Resolves #

## Description

- 백엔드 로그인 로직 구현(스캠 로그인 람다 호출 제외)

## Check List

- [o]  PR 제목을 커밋 규칙에 맞게 작성
- [o]  PR에 해당되는 Issue를 연결 완료
- [o]  적절한 라벨 설정
- [o]  작업한 사람 모두를 Assign
- [o]  작업한 팀에게 Code Review 요청 (Reviewer 등록)
- [o]  `main` 브랜치의 최신 상태를 반영하고 있는지 확인

## Screenshot

2023-08-30 15:17 UTC, kkanggu requested changes
ERD 바꾸신 부분은 별도의 Issue로 정리 부탁드립니다.

2023-08-30 15:17 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/common/security/component/JwtVerifier.kt
> -
이거 없으면 테스트 빡세지고 Swagger 사용 불가인거 인지하셨나요

2023-08-30 15:17 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/common/security/component/JwtVerifier.kt
> +                    TokenDto(userId = 1, userRole = "STUDENT")
이렇게 하면 토큰 위변조하여 악의적인 액세스가 가능할 것 같습니다.

2023-08-30 15:17 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/common/security/component/JwtVerifier.kt
> +            return verification
return when 으로 더욱 간단히 처리가 가능하지 않을까요?

2023-08-30 15:17 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/common/security/component/TokenParser.kt
> +        ?: throw DefaultException(ErrorCode.TOKEN_INVALID, HttpStatus.BAD_REQUEST)
DefaultException의 기본 HttpStatus는 `BAD_REQUEST`이기에 간단히 표현 가능할 것 같습니다.

2023-08-30 15:17 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/common/security/component/TokenProvider.kt
> +    @Value("\${app.jwt.refreshTokenValidMS}") private val refreshTokenValidMiS: Long = 0
끝에 `MiS`로 되어있는데 `MS`가 맞지 않나요?

2023-08-30 15:17 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/auth/controller/AuthController.kt
> +            )
signUpRequest의 모든 값을 넘겨주는 것 같은데, 해당 Request 자체를 넘겨주어 service에서 처리하는게 더 가독성이 좋을 것 같습니다.

2023-08-30 15:17 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/auth/controller/AuthController.kt
> +            )
여기서 사용되는 signInRequest.password는 클라에서 먼저 암호화하여 보내주나요?

2023-08-30 15:17 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/auth/service/AuthService.kt
> +        user.refreshToken = refreshToken.token
Entity에서 처리하는 로직이 아니며, 이후 별도의 save 작업이 없는데 DB에도 해당 토큰이 정상적으로 저장되나요?

2023-08-31 05:34 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/common/security/component/JwtVerifier.kt
> +                    TokenDto(userId = 1, userRole = "STUDENT")
이게 위에랑 동일한 상황인데 로그인은 토큰을 안받아서 테스트하기가 애매했어요... 좀 곤란하네여 프론트는 스웨거 쓸 때 무조건 로그인하고 하라고 해야하나

2023-08-31 05:34 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/common/security/component/JwtVerifier.kt
> +            return verification
👍

2023-08-31 05:35 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/common/security/component/TokenProvider.kt
> +    @Value("\${app.jwt.refreshTokenValidMS}") private val refreshTokenValidMiS: Long = 0
오

2023-08-31 05:36 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/auth/controller/AuthController.kt
> +            )
가독성 측면에서는 컨트롤러에서 각 변수를 분리해서 넘겨주는게 서비스 비즈니스 로직 작성에 더 좋아보입니다. 어떻게 생각하시나요?

2023-08-31 05:37 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/auth/controller/AuthController.kt
> +            )
클라이언트는 raw string으로 보내야해요

2023-08-31 05:38 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/auth/service/AuthService.kt
> +        user.refreshToken = refreshToken.token
user가 db에서 조회한 엔티티의 영속성 컨텍스트에 포함되어 이렇게만 해줘도 jpa가 자동으로 업데이트 해주더라구요

2023-08-31 05:39 UTC, HwanGonJang commented
노션 인프라 페이지에 db 스키마 변경에 대해서 업데이트 할 수 있도록 작성해놨습니다!

2023-09-03 23:53 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/auth/controller/AuthController.kt
> +            )
개인적으로 Request 통짜로 넘겨주는걸 선호합니다. 세세하게 풀어서 작성하면 바로 보이긴 하지만 그만큼 코드 양도 길어지며, 로직 변동이 있을 때 소스 변경하는 부분이 많아지는 것 같습니다.
또한 파라미터의 개수도 생각보다 중요할 것 같습니다. 1-2개라면 큰 차이가 없겠으나, 파라미터 개수가 많아지면 그만큼 파라미터가 차지하는 비중이 증가합니다. 극단적으로 DTO 없이 몇십개의 파라미터를 그대로 넘겨주는 상황을 가정하면 보통 DTO를 이용할텐데, 이 경우 DTO로 전환하는 기준을 고려해봐야 하기도 할 것 같습니다.

2023-09-03 23:54 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/common/security/component/JwtVerifier.kt
> +                    TokenDto(userId = 1, userRole = "STUDENT")
최초 로그인 시 토큰은 당연히 없을 것이고, 로그인 페이지로 리다이렉트 하는 등 방법은 많을 것 같습니다.
이전에 프로필로 통과한 이유는 개발 환경에서 로그인 자체가 귀찮아서이기도 합니다.

2023-09-03 23:56 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/auth/controller/AuthController.kt
> +            )
암호화 없이 민감한 개인정보를 주고받는게 과연 좋은 방법일까요? 보안 측면에서 큰 취약점이 될 가능성이 높아보입니다.

2023-09-04 05:00 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/auth/controller/AuthController.kt
> +            )
인코딩 정도는 할 수 있지만 결국 사용하려면 복호화가 되는 알고리즘을 사용해야 하긴 할 것 같네요

2023-09-04 05:01 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/auth/controller/AuthController.kt
> +            )
그렇군여... 그럼 저희 플젝은 그렇게하는걸로 컨벤션 맞추는게 좋을 것 같네요!

2023-09-04 09:33 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/common/security/component/JwtVerifier.kt
> +                    TokenDto(userId = 1, userRole = "STUDENT")
롤백했습니다 하지만 이 경우도 결국 dev 스웨거에 접근만 되면 모든 요청이 뚫리는 거라 보안적으로 추가 장치가 필요해보입니다

2023-09-04 09:35 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/auth/controller/AuthController.kt
> +            )
저는 사실 저희 정도 규모의 프로젝트면 https 설정으로도 충분하다고 생각하긴 합니다

2023-09-04 10:34 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/common/security/component/JwtVerifier.kt
> +                    TokenDto(userId = 1, userRole = "STUDENT")
dev 및 prod가 거의 격리되어 있는 상황 아닌가요? 개발 서버 Swagger 접근도 url이 다르며, 개발 서버에 있는 데이터는 더미 데이터라 문제될게 딱히 없어보이긴 합니다.

2023-09-04 10:36 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/auth/controller/AuthController.kt
> +            )
데이터를 받자마자 단방향 암호화하는 것이 아닌, 서버로 넘어가서야 처리가 되는 플로우이기에 법적 문제가 발생할 여지가 있어보이네요.

2023-09-04 10:38 UTC, kkanggu approved these changes
고생하셨습니다.

2023-11-10 08:57 UTC, HwanGonJang commented
유저 테이블 접근이 안돼서 보류입니다

2023-11-21 13:13 UTC, merged