[#21] 일정 수정 API
DaITssu/daitssu-api pull request #43
Opened 2023-09-09 13:26 UTC by swdevsw98

## Issue

- Resolves #21 

## Description

- 캘린더 수정 기능 구현
- 테스트 구현
- response에 id 제공하지 않았던 response들 수정
- 반복적으로 사용되는 date 검사 함수로 추출
- 수정에 완료/미완료는 변수 어떻게 할지 몰라 미구현

## Check List

- [ ]  PR 제목을 커밋 규칙에 맞게 작성
- [ ]  PR에 해당되는 Issue를 연결 완료
- [ ]  적절한 라벨 설정
- [ ]  작업한 사람 모두를 Assign
- [ ]  작업한 팀에게 Code Review 요청 (Reviewer 등록)
- [ ]  `main` 브랜치의 최신 상태를 반영하고 있는지 확인

## Screenshot

2023-09-10 11:58 UTC, kkanggu requested changes

2023-09-10 11:58 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
> +            .also { calendarRepository.save(calendar) }
calendar 갱신 후 별도의 save 작업이 이뤄지는데, save 없이 갱신만 해도 실제 Entity에 반영이 안 되나요?

2023-09-10 11:58 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
> +    }
`checkDate`는 검증의 용도로 이해하기 쉬우나, 실제 작업은 타입 변환이 이루어집니다. 메소드 이름이 직관적이지 않은 것 같습니다.

2023-09-10 11:58 UTC, kkanggu commented on src/test/kotlin/com/example/daitssuapi/domain/course/controller/CourseControllerTest.kt
> +        mockMvc.perform(get("$url/$wrongUserId"))
중복 구문 같습니다.

2023-09-10 11:58 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
> +        val formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
조회는 월별로 이루어지는 것으로 알고 있는데, 날짜 및 시각이 필요한가요?

2023-09-11 01:40 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
> +            .also { calendarRepository.save(calendar) }
also문을 제거하고 실행하면 반영이 안되긴합니다! 혹시 다른방법이 있을까요?

2023-09-11 01:40 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
> +    }
수정했습니다!

2023-09-11 01:40 UTC, swdevsw98 commented on src/test/kotlin/com/example/daitssuapi/domain/course/controller/CourseControllerTest.kt
> +        mockMvc.perform(get("$url/$wrongUserId"))
수정했습니다!

2023-09-11 01:41 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
> +        val formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
이게 조회는 월별이 맞는데 생성이나 수정에서 날짜와 시간까지 존재해서 통일했는데, 조회만 따로 년, 월만 체크하게 만들라고 하시면 그렇게 진행하겠습니다!

2023-09-11 09:54 UTC, HwanGonJang reviewed
굿굿

2023-09-11 09:54 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
> +        val formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
저는 통일해서 가도 괜찮을 것 같아요

2023-09-11 09:54 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
> +        )
```suggestion
return calendar
            .also { 
                it.name = calendarRequest.name
                it.type = calendarRequest.type
                it.course = calendarRequest.course
                it.dueAt = dateTime
            }
            .let {
                CalendarResponse(
                    id = calendar.id,
                    type = calendar.type,
                    dueAt = calendar.dueAt,
                    name = calendar.name
                )
            }
```

요런 느낌으로 하면 저장 후 리턴이 안될까요?

2023-09-11 12:14 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
> +            .also { calendarRepository.save(calendar) }
반영이 안 되면 현재 방식이 나을 것 같네요.

2023-09-11 12:15 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
> +        val formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
생성 및 시간은 필요하다면 전부 받는게 맞는 방향 같습니다. 다만 조회할 때 필요없는 정보까지 넘겨주어야 하기에 사용하기에 불편할 것 같습니다.

2023-09-11 12:18 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
> +    fun checkDateReturnLocalDateTime(dueAt: String) : LocalDateTime {
검증 및 날짜 변환으로 이해되지만 메소드명이 길다고 인식되네요. `checkAndReturnDate`와 같이 간단하게 표현하여도 좋을 것 같습니다. 반환 타입을 명시해줄 필요는 없어보입니다.

2023-09-12 10:30 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
> +            .also { calendarRepository.save(calendar) }
넵

2023-09-12 10:31 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
> +        val formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
그럼 조회(년, 월) / 생성 및 수정(년, 월, 일, 시간) 이렇게 나눠서 진행할까요?

2023-09-12 10:33 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
> +        )
아마 안될꺼 같습니다 달아주신 also문이 updateCalendar 함수와 같은 실행인데
save를 안하면 조회시 데이터가 반영이 안되어있더라구요!

2023-09-12 10:33 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
> +    fun checkDateReturnLocalDateTime(dueAt: String) : LocalDateTime {
수정했습니다!

2023-09-12 13:39 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
> +        val formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
그렇게 나누는게 사용하는 입장에서 자연스러운 방향인 것 같습니다.

2023-09-13 05:36 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/course/service/CourseService.kt
> +        val formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
수정했습니다

2023-09-17 14:58 UTC, kkanggu approved these changes
고생하셨습니다. Conflict 해결이 어려우면 cherry-pick 이용해서 별도 PR로 작업 부탁드려요.

2023-09-18 06:15 UTC, merged