Feature/S3-및-이미지-핸들링
DaITssu/daitssu-api pull request #50
Opened 2023-09-19 12:10 UTC by HwanGonJang

급하게 하느라 커밋 분리를 못했네요...

## Issue
[커뮤니티] s3 사진 저장 기능 추가

## Description
* s3 생성 및 이미지 추가
* 단일 조회 스키마에 이미지 경로 추가
-

## Check List

- [ v ]  PR 제목을 커밋 규칙에 맞게 작성
- [ v ]  PR에 해당되는 Issue를 연결 완료
- [ v ]  적절한 라벨 설정
- [ v ]  작업한 사람 모두를 Assign
- [ v ]  작업한 팀에게 Code Review 요청 (Reviewer 등록)
- [ v ]  `main` 브랜치의 최신 상태를 반영하고 있는지 확인

## Screenshot
<img width="497" alt="image" src="https://github.com/DaITssu/daitssu-api/assets/33739448/08936f8b-cf96-48a5-a69f-e3a513b15c63">  

생성 api
post 부분은 response body 없애기로 해서 수정했습니다.

<img width="1121" alt="image" src="https://github.com/DaITssu/daitssu-api/assets/33739448/7b1ea7f9-ea42-4f03-bf4b-ef82a0eb3310">
단일 조회 api

2023-09-20 14:17 UTC, kkanggu requested changes
일부 항목으로 인해 approve를 하지 않았습니다.

2023-09-20 14:17 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/infra/service/S3Service.kt
> +        val extension = if (fileName.substringAfterLast(".") in listOf("webp", "WEBP")) "webp" else "jpg"
webp, WEBP를 가지는 list를 별도의 변수로 분리하는것도 좋아보이네요

2023-09-20 14:17 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/infra/service/S3Service.kt
> +            .toString() + "-" + fileNameExceptExtension + "." + extension
한줄로 표현이 가능한데 분리한 이유는 너무 길어져서일까요?

2023-09-20 14:17 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/infra/service/S3Service.kt
> +        )
예외 처리가 되지 않았는데, 의도하신 부분일까요?

2023-09-20 14:17 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/infra/service/S3Service.kt
> +    }
상수를 companion object로 선언했는데, 다른 곳에서도 사용된다면 별도의 Constants.kt 등으로 분리하는것도 좋아보입니다.

2023-09-20 14:17 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/main/model/entity/Article.kt
> +}
Entity간의 맵핑은 현재 프로젝트에서는 () 내부에서 진행했는데, {}로 뺀 이유가 있을까요?

2023-09-20 14:17 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/main/controller/ArticleController.kt
> +    }
게시글 생성에 성공하였는지 알려주어야 할 것 같습니다. 실패한다면 수동으로 다시 작업해야 하지 않을까요?

2023-09-20 14:17 UTC, kkanggu commented on src/test/kotlin/com/example/daitssuapi/domain/main/controller/ArticleControllerTest.kt
>      }
생성 후 삭제를 하지 않으면 무의미한 파일이 쌓이지 않나요?

2023-09-22 05:16 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/infra/service/S3Service.kt
> +        val extension = if (fileName.substringAfterLast(".") in listOf("webp", "WEBP")) "webp" else "jpg"
좋아용

2023-09-22 05:17 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/infra/service/S3Service.kt
> +            .toString() + "-" + fileNameExceptExtension + "." + extension
제가 인텔리제이 설정에서 몇줄이상은 자동 줄바꿈을 해서 그렇습니다. 줄바꿈이 없는게 더 좋을까요? 너무 길긴해요

2023-09-22 05:21 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/infra/service/S3Service.kt
> +        )
이 부분은 aws와 연결되어있기 때문에 저장이 안되면 예외처리가 아닌 그냥 서버에서 500오류를 반환하는게 맞다고 생각했습니다.  아니면 aws에서 반환하는 특정 오류케이스를 잡아서 try catch를 하는게 나을까요? 어떤 방향으로 생각하고 계신가용

이 부분 생각해서 직접 Url 디비에 넣을 때 오류가 나면 s3에서도 지우는 로직 추가했습니다.

2023-09-22 05:25 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/main/model/entity/Article.kt
> +}
article image를 저장할 때 외래키라 article을 받아서 이렇게 했어요
  
```
    val article = Article(
          topic = articleCreateRequest.topic,
          title = articleCreateRequest.title,
          content = articleCreateRequest.content,
          writer = user
      )

      val articleImages = imageUrls.map {
          ArticleImage(
              url = it,
              article = article
          )
      }
```

2023-09-22 05:28 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/main/model/entity/Article.kt
> +}
지금 보니까 생성할 때 매핑 된 애들은 생성자에 안넣고 외래키에 해당하는 테이블을 저장할 때 넣어주네요. 이런식으로 해도 동작하나요?

2023-09-22 05:30 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/main/controller/ArticleController.kt
> +    }
수정했는데 이렇게 하면 될까요? 프론트에서는 200 상태코드만 달라고 헀습니다.

2023-09-24 10:50 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/infra/service/S3Service.kt
> +            .toString() + "-" + fileNameExceptExtension + "." + extension
```kotlin
val key1 = "$profile/$domain/$userId/image/"
val key2 = "${LocalDateTime.now()}-$fileNameExceptExtension.$extension"
```

처럼 2개로 나누는건 어떤가요? key1 부분은 유저 구분, key2는 각 파일 구분으로 볼 수도 있을 것 같아요.

2023-09-24 10:52 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/infra/service/S3Service.kt
> +        )
단순 500으로 떨어지면 해당 API를 사용하는 입장에서는 정말 서버 이슈인지, 혹은 S3로 인한 이슈인지 파악이 어려울 것 같습니다. 저라면 catch 후 Custom Exception으로 처리할 것 같아요.

2023-09-24 10:54 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/main/model/entity/Article.kt
> +}
정확히 뭘 의미하는지 이해하지 못 하였지만, 저 부분도 () 내부로 옮겨서 처리해도 잘 되는 것으로 알고 있습니다.

2023-09-24 10:57 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/main/controller/ArticleController.kt
> +    }
단순 200 return이라면 넘겨줄 data가 필요할까요?
또한 Response에서의 code == ErrorCode이기에 `code = 0`이 맞는 것 같습니다.

2023-09-24 10:59 UTC, kkanggu approved these changes

2023-09-24 10:59 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/infra/constants/S3Bucket.kt
> +}
이렇게 URL을 명시한다면, 추후 HTML 파일을 가져올 때 public 접근을 막아야할 것 같습니다.

2023-09-24 10:59 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/common/constants/FileFormat.kt
> +}
```kotlin
const val webp = listof("WEBP", "webp")
```

가 더욱 나을 것 같습니다. object 안에 넣을 이유가 없어보여요.

2023-09-27 01:21 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/main/model/entity/Article.kt
> +}
한구님 이거 저 매핑을 생성자로 옮기면 article을 생성하기 전에 articleImages를 생성해야 생성자에 넣어줄 수 있는데, 외래키 순서 상 불가능하잖아요? 양방향 매핑 관계인데 가능한가요? 아님 Nullable로 처리?

2023-09-27 05:02 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/main/controller/ArticleController.kt
> +    }
아하 그렇네요

2023-09-27 05:03 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/common/constants/FileFormat.kt
> +}
이거 const는 List 타입을 못받더라구요

2023-09-27 05:19 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/infra/constants/S3Bucket.kt
> +}
환경변수로 분리할게요

2023-09-27 05:30 UTC, HwanGonJang commented on src/test/kotlin/com/example/daitssuapi/domain/main/controller/ArticleControllerTest.kt
>      }
수현님이 작성한거라 안맞는 부분이 있네요 삭제하고 다시 만드는게 좋을 거 같아요

2023-09-27 05:32 UTC, merged