[#49] 공지사항/펀시스템 조회수, 카테고리별 검색 추가
DaITssu/daitssu-api pull request #54
Opened 2023-09-25 11:46 UTC by JooHui-void

## Issue

- Resolves #49 

## Description

- h2 데이터베이스 테스팅시 postgresql 문법으로 먹어서 나는 오류 수정
- 환곤님 요청 ( 리스트 get시 필요한 데이터만 가져오기) response 따로 제작
- views 추가 (진짜 데이터베이스에도 반영 필요함, 요청서 쓸게요)
- 카테고리별 검색기능 추가 

## Check List

- [ ]  PR 제목을 커밋 규칙에 맞게 작성
- [ ]  PR에 해당되는 Issue를 연결 완료
- [ ]  적절한 라벨 설정
- [ ]  작업한 사람 모두를 Assign
- [ ]  작업한 팀에게 Code Review 요청 (Reviewer 등록)
- [ ]  `main` 브랜치의 최신 상태를 반영하고 있는지 확인

## Screenshot

2023-09-25 12:12 UTC, kkanggu requested changes

2023-09-25 12:12 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/notice/controller/FunSystemController.kt
> +        @RequestParam(required = false) searchKeyword : String?
Nullable이라 없다면 null로 설정될텐데, required 옵션이 필수일까요?

2023-09-25 12:12 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/notice/controller/FunSystemController.kt
> +    }
공지 전체 가져오기 / 키워드를 이용한 공지 검색
두 기능을 하나의 Controller로 처리하고 있는데요. 두 기능을 분리하는게 더 좋아보입니다.

2023-09-25 12:12 UTC, kkanggu commented on src/test/resources/data.sql
> +    (5,'공지사항5','5번 공지 내용입니다!!','EXPERIENTIAL_ACTIVITIES','http://google.com','1000-01-01 00:00:00','1000-01-01 00:00:00',0);
테스트 전체 잘 도는지 확인 바랍니다.

2023-09-27 01:13 UTC, HwanGonJang reviewed
수고하셨습니다! 리뷰 확인해주세요~

2023-09-27 01:13 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/notice/model/repository/FunSystemRepository.kt
> +    fun updateViewsById(@Param("id") id: Long)
쿼리 어노테이션은 안쓰는게 좋아요!

2023-09-27 01:13 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/notice/model/repository/NoticeRepository.kt
> +    fun updateViewsById(@Param("id") id: Long)
ibid

2023-09-27 01:13 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/notice/service/FunSystemService.kt
> +    fun updateViews( id:Long ) { funSystemRepository.updateViewsById(id)}
@Query는 에러핸들링이 어려워서 사용을 지양하는게 좋습니다. 보통은 id 값으로 findByIdOrNull을 호출해 들고온 후 null이면 에러처리, 값이 있다면 해당 엔티티 값을 코드상에서 수정하고 save하는 방식으로 합니다!

```
fun updateViews( id:Long ) { 
    val funSystem = funSystemRepository.findByIdOrNull(id) ?: throw FunSystemNotFound()
    funSystem.views += 1
    funSystemRepository.save(funSystem)
}
```  

영속성 컨텍스트로 save를 하지 않아도 자동으로 업데이트 되긴 합니다 영속성 컨텍스트 관련해서 찾아보시면 도움이 될거에요

2023-09-27 01:13 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/notice/service/FunSystemService.kt
> +    ): FunSystemPageResponse {
CRUD중 CUD를 담당하는 서비스 메소드에는 디비 일관성을 위해 `@Transactional`을 붙여주는게 좋습니다. 이건 그냥 버릇처럼 써주세용

2023-09-30 14:50 UTC, JooHui-void commented on src/main/kotlin/com/example/daitssuapi/domain/notice/controller/FunSystemController.kt
> +    }
반영하겠습니다!

2023-09-30 14:53 UTC, JooHui-void commented on src/main/kotlin/com/example/daitssuapi/domain/notice/model/repository/FunSystemRepository.kt
> +    fun updateViewsById(@Param("id") id: Long)
Query를 안쓰고 다른 방식으로 하려면 어떤걸 사용하는 것이 좋을까요..??

2023-10-02 07:58 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/notice/model/repository/FunSystemRepository.kt
> +    fun updateViewsById(@Param("id") id: Long)
단순 업데이트는 제가 아래 리뷰해드린대로 하시면 됩니다

2023-10-07 12:17 UTC, JooHui-void commented on src/main/kotlin/com/example/daitssuapi/domain/notice/service/FunSystemService.kt
> +    fun updateViews( id:Long ) { funSystemRepository.updateViewsById(id)}
헉 감사합니다!!!! 한번 알아볼게요

2023-10-07 13:50 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/notice/service/FunSystemService.kt
> +    ): FunSystemPageResponse {
조회수 update 기능을 말씀하시는 것 같은데, 이건 저도 주희님과 동일하게 `@Transactional` 생략이 나을 것 같습니다.
저희 서비스에서의 조회수는 없어도 될 정도의 부가 기능이며, Tx를 이용하여 정합성을 빡세게 관리할만한 요소는 아니라고 판단하였습니다. 오히려 Tx로 인해 게시글 조회 기능에 영향을 줄 수도 있기에, 조회수가 일부 누락이 되더라도 Tx를 제외하는게 나은 것 같습니다.

2023-10-08 06:59 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/notice/service/FunSystemService.kt
> +    ): FunSystemPageResponse {
아하 그런 관점도 있겠네요! 저는 그냥 무시정으로 다는게 습관이 돼서ㅋㅋ

2023-10-16 11:22 UTC, HwanGonJang approved these changes
수고하셨습니다! 댓글 기능 추가된 후에 병합해야 하는 기능이었죠? 댓글 반영 후에 작업하시고 병합하면 될 것 같아요

2023-10-16 11:52 UTC, kkanggu commented
병합 과정에서 생성된 문자열이 그대로 남아있습니다. 확인 후 수정 부탁드립니다.

2023-10-26 14:49 UTC, JooHui-void commented
고쳐뒀습니다!

2023-10-29 12:05 UTC, kkanggu requested changes
NoticeController에서 테스트가 실패하고 있습니다. SQL만 수정하면 해결될 것 같습니다.

2023-11-06 14:14 UTC, kkanggu approved these changes
고생하셨습니다.

2023-11-11 04:53 UTC, merged