[#45] 오늘 마감 일정 조회
DaITssu/daitssu-api pull request #55
Opened 2023-09-27 05:38 UTC by swdevsw98

## Issue

- Resolves #45 

## Description

- reflection 에러 발생

## Check List

- [ ]  PR 제목을 커밋 규칙에 맞게 작성
- [ ]  PR에 해당되는 Issue를 연결 완료
- [ ]  적절한 라벨 설정
- [ ]  작업한 사람 모두를 Assign
- [ ]  작업한 팀에게 Code Review 요청 (Reviewer 등록)
- [ ]  `main` 브랜치의 최신 상태를 반영하고 있는지 확인

## Screenshot

2023-10-01 11:39 UTC, HwanGonJang reviewed
아 제가 리뷰하고 펜딩으로 놔뒀네요...

2023-10-01 11:39 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/course/dto/response/TodayCalendarData.kt
> +data class TodayCalendarData (
이런 커스텀 data class는 뒤에 Dto suffix로 붙여주세요!

2023-10-01 11:39 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/course/model/repository/CalendarRepository.kt
> +    )
보통 `@Query` 어노테이션은 db에 종속되고 에러핸들링이 어려워 사용을 지양합니다. 하지만 이런 group by나 여러번의 조인이 필요한 쿼리의 경우가 있는데요, 그래서 자주 사용하는 툴이 query dsl입니다. 이 부분은 쿼리가 복잡해서 request change를 요청하진 않겠지만 관심이 있으시면 한 전 적용해보는 것도 좋을 것 같아요. 한번 노티 주시면 이슈 할당에 참고할게요!

2023-10-01 11:39 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/course/model/repository/CalendarRepository.kt
> +    ): List<TodayCalendarMapping>
이건 처음보는 jpa 함수네요. 이런식으로 히면 자동으로 해당 파라미터에 where절로 적용해주나요?

2023-10-01 12:19 UTC, kkanggu requested changes
기능과 소스가 맞지 않아 Approve하지 않았습니다.

2023-10-01 12:19 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/course/controller/CourseController.kt
> +        Response(data = courseService.updateCalendar(calendarRequest = calendarRequest, calendarId = calendarId))
일정 조회 기능인데 왜 update를 진행할까요?

2023-10-01 12:19 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/course/model/repository/CalendarRepository.kt
> +    )
메소드명이 너무 길어질 경우 Query Annotation 붙여서 Native Query로 작성하기도 합니다. 다만 위 Query의 경우, 너무 길고 복잡하기에 유지 보수가 매우 어려워집니다. 간단한 Query로 가져온 후, 상세 로직을 소스로 풀어내는게 더욱 좋아보입니다.

2023-10-01 12:19 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/course/model/repository/CalendarRepository.kt
> +    ): List<TodayCalendarMapping>
JPA 이용 시, Entity가 아닌 특정 데이터만 가져올 때 사용하는 방식으로 기억합니다. 위와 같이 별도의 Dto + `getFOO` 메소드로 받아오거나, 다른 방식도 존재하긴 합니다.

2023-10-02 06:39 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/course/dto/response/TodayCalendarData.kt
> +data class TodayCalendarData (
네

2023-10-02 06:40 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/course/model/repository/CalendarRepository.kt
> +    )
쪼개서 코드로 수정해보겠습니다

2023-10-02 06:41 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/course/model/repository/CalendarRepository.kt
> +    ): List<TodayCalendarMapping>
커스텀 메서드인데 네이밍하면 sql에 값으로 쓸 수 있어서 저렇게 했습니다 저는 인터페이스로 get해서 가져왔습니다. 엔티티로 가져와서 바꾸는 방식으로 수정하겠습니다

2023-10-02 06:42 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/course/controller/CourseController.kt
> +        Response(data = courseService.updateCalendar(calendarRequest = calendarRequest, calendarId = calendarId))
전에 했던 일정 수정 커밋인거 같습니다

2023-10-03 05:29 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/course/controller/CourseController.kt
> +        Response(data = courseService.updateCalendar(calendarRequest = calendarRequest, calendarId = calendarId))
여러 기능이 섞여있어 추후 변경 이력 추적이 어려워집니다. 해당 기능도 PR이 필요하면 별도의 PR로 분리해주시고, 현 PR에서는 해당 기능 제거 부탁드립니다.

2023-10-03 10:31 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/course/controller/CourseController.kt
> +        Response(data = courseService.updateCalendar(calendarRequest = calendarRequest, calendarId = calendarId))
전에 머지 끝난 커밋인데 기록이 안지워지는데 어떻게 하나요? 새로 브랜치를 파서 4개만 푸쉬해도 18개가 같이 따라옵니다

2023-10-03 11:29 UTC, swdevsw98 commented
병합 완료된 커밋 지우기 위해 클로즈

2023-10-03 11:29 UTC, closed without merging