[커뮤니티] 게시물 수정
DaITssu/daitssu-api pull request #70
Opened 2023-10-06 22:37 UTC by sebbbin

## Issue

- Resolves #56 

## Description

- 커뮤니티의 게시물을 수정해주는 api

## Check List

- [ ]  PR 제목을 커밋 규칙에 맞게 작성
- [ ]  PR에 해당되는 Issue를 연결 완료
- [ ]  적절한 라벨 설정
- [ ]  작업한 사람 모두를 Assign
- [ ]  작업한 팀에게 Code Review 요청 (Reviewer 등록)
- [ ]  `main` 브랜치의 최신 상태를 반영하고 있는지 확인

## Screenshot

2023-10-08 07:05 UTC, HwanGonJang reviewed
![작전타임](https://github.com/DaITssu/daitssu-api/assets/33739448/b17cff5b-7247-4347-a11a-26f6a8a642af)

2023-10-08 07:05 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/main/service/ArticleService.kt
> +        article.content = articleUpdateRequest.content.toString()
이거 nullbale String인데 toString 쓰면 null일 때는 "null" 이렇게 박히는걸로 알아요
`articleUpdateRequest?.let { article.title = it.title }` 이렇게 하거나 null일 때 핸들링 해주세영

2023-10-08 07:05 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/main/dto/request/ArticleUpdateRequest.kt
> +        val title: String?,
`val title: String? = null` 이렇게 하면 가독성이 좋아지긴하는데 이건 뭐 개취입니당

2023-10-08 07:05 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/domain/main/service/ArticleService.kt
> +        }
```
.onFailure {
            throw DefaultException(errorCode = ErrorCode.S3_UPLOAD_FAILED)
        }
```
이거 안해주면 runCatching 의미가 크게 없을거같아여

2023-10-09 14:23 UTC, kkanggu requested changes
나름 영향도가 높은 기능이기에 테스트 코드 추가 작성이 필요해보입니다.

2023-10-09 14:23 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/main/service/ArticleService.kt
> +        }
기존 이미지를 그대로 놔둘 경우, body로 해당 이미지도 포함이 되어있을까요?
만약 아니라면 기존 이미지가 없어지지 않고 게시글에 노출이 되는 이슈가 존재할 것 같습니다.

2023-12-31 13:34 UTC, closed without merging