[#60] 커뮤니티 topic 분류로 조회하기 api
DaITssu/daitssu-api pull request #72
Opened 2023-10-09 13:59 UTC by JooHui-void

## Issue

- Resolves #60 

## Description

- 커뮤니티 topic을 이용하여 조회하는 api

## Check List

- [ ]  PR 제목을 커밋 규칙에 맞게 작성
- [ ]  PR에 해당되는 Issue를 연결 완료
- [ ]  적절한 라벨 설정
- [ ]  작업한 사람 모두를 Assign
- [ ]  작업한 팀에게 Code Review 요청 (Reviewer 등록)
- [ ]  `main` 브랜치의 최신 상태를 반영하고 있는지 확인

## Screenshot

2023-10-09 14:19 UTC, kkanggu requested changes
코멘트로 남긴 부분만 수정하면 될 것 같습니다.

2023-10-09 14:19 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/main/controller/ArticleController.kt
> +        }
Controller에서 처음부터 Topic으로 받아오는데, if 로직이 true가 되는 상황이 존재할까요?

2023-10-09 14:19 UTC, kkanggu commented on src/test/kotlin/com/example/daitssuapi/domain/main/controller/ArticleControllerTest.kt
> +        val article = articleRepository.findAll()[1] //QUESTION 가진 article 나와야함
테스트 데이터가 바뀌면 테스트가 터지는 상황입니다. `findAll().filter { it.topic == Topic.QUESTION }` 처럼 가져오면 좋을 것 같습니다.

2023-10-09 14:19 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/main/controller/ArticleController.kt
> +        @PathVariable topic: Topic,
이 부분은 `PathVariable`로 경로를 잡기보다는 `/topic` 하위에서 Parameter로 구분하는게 맞는 것 같습니다.

2023-10-13 13:15 UTC, JooHui-void commented on src/main/kotlin/com/example/daitssuapi/domain/main/controller/ArticleController.kt
> +        }
뒤에 붙는 문장 다 가져오는줄 알았는데 Topic만 알아서 받아오게 되네요..! 알려주셔서 감사합니다

2023-10-16 11:37 UTC, JooHui-void commented on src/test/kotlin/com/example/daitssuapi/domain/main/controller/ArticleControllerTest.kt
> +        val article = articleRepository.findAll()[1] //QUESTION 가진 article 나와야함
반영하겠습니다!

2023-12-06 15:51 UTC, JooHui-void commented on src/main/kotlin/com/example/daitssuapi/domain/main/controller/ArticleController.kt
> +        @PathVariable topic: Topic,
확인했습니다!

2023-12-10 13:47 UTC, closed without merging

2023-12-10 13:47 UTC, kkanggu commented
Conflict이 많아 수동 작업 중 이슈 발생 가능성이 높기에 기존 PR Close