fix/traceId-추가하기
DaITssu/daitssu-api pull request #73
Opened 2023-10-10 12:55 UTC by HwanGonJang

## Issue

- Resolves #

## Description

- 에러처리를 위한 traceId 

## Check List

- [x]  PR 제목을 커밋 규칙에 맞게 작성
- [x]  PR에 해당되는 Issue를 연결 완료
- [x]  적절한 라벨 설정
- [x]  작업한 사람 모두를 Assign
- [x]  작업한 팀에게 Code Review 요청 (Reviewer 등록)
- [x]  `main` 브랜치의 최신 상태를 반영하고 있는지 확인

## Screenshot

2023-10-10 14:18 UTC, kkanggu requested changes
당장 예외 추적에는 조금이라도 도움이 될지라도, 장기적으로 바라보면 레거시로 남을 가능성이 높은 것 같습니다. 예외 추적 용도라면 `mdc`를 이용하여 Request가 들어올 때 mdc를 설정하는게 좋을 것 같습니다.

2023-10-10 14:18 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/common/exception/ExceptionHandler.kt
> +        val traceId = traceIdResolver.getTraceIdOrNull()
예외가 발생할 때 traceId를 가져오는데, 이를 다른 로그에서는 확인할 수 없는 상황입니다.

2023-10-10 14:18 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/common/dto/Response.kt
> +    val timestamp: LocalDateTime = LocalDateTime.now(),
로그를 찍을 때 시간은 함께 찍히며, 응답에서 traceId를 넘겨줄 이유가 없어보입니다. 예외 추적 용도라면 `mdc`를 이용하는것이 더 나아보입니다.

2023-10-16 11:19 UTC, HwanGonJang commented
요 pr은 드래프트로 해놓을게요 나중에 논의해보죠

2023-10-16 12:47 UTC, HwanGonJang commented on src/main/kotlin/com/example/daitssuapi/common/exception/ExceptionHandler.kt
> +        val traceId = traceIdResolver.getTraceIdOrNull()
굿

2023-10-16 12:47 UTC, closed without merging