[#82] 스크랩한 글 조회
DaITssu/daitssu-api pull request #87
Opened 2023-10-18 02:58 UTC by swdevsw98

## Issue

- Resolves #82 

## Description

-스크랩한 글 조회 기능, 테스트

## Check List

- [ ]  PR 제목을 커밋 규칙에 맞게 작성
- [ ]  PR에 해당되는 Issue를 연결 완료
- [ ]  적절한 라벨 설정
- [ ]  작업한 사람 모두를 Assign
- [ ]  작업한 팀에게 Code Review 요청 (Reviewer 등록)
- [ ]  `main` 브랜치의 최신 상태를 반영하고 있는지 확인

## Screenshot

2023-10-18 03:04 UTC, swdevsw98 commented
전에 커밋이 머지 되지않아 커밋이 4개가 올라왔습니다. 선택해서 봐주시거나 아니면 머지 후 다시 PR 올리겠습니다!

2023-10-21 09:46 UTC, kkanggu requested changes
대상 Branch 변경 혹은 해당 기능만 존재하는 PR로 분리 부탁드립니다.

2023-10-21 09:46 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/main/model/repository/ArticleRepository.kt
> +    fun findAllByWriter(writer: User) : List<Article>
`내가 쓴 글 조회` 기능으로 추측되는데, 두 기능이 하나의 PR에 섞여있어 리뷰가 어렵습니다. commit을 따로 분리하기 어려울 경우, 해당 기능의 PR(`feat/#80`) 으로 대상 branch를 변경하는 것이 더욱 좋을 것 같습니다.

2023-10-21 13:39 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/main/model/repository/ArticleRepository.kt
> +    fun findAllByWriter(writer: User) : List<Article>
브랜치를 따로 파서 커밋 후 진행했는데 계속 따라와서 어떻게 제거하는 지 모르겠습니다. 리베이스도 해보고 머지도 해보고 강제 푸쉬를 해봐도 사라지지가 않네요. 이전꺼 머지되면 다시 올리겠습니다

2023-10-21 13:56 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/main/model/repository/ArticleRepository.kt
> +    fun findAllByWriter(writer: User) : List<Article>
최상단 제목 Edit을 누르면 대상 Branch 변경이 가능합니다. develop이 아닌 `feat/#80` 으로 변경하시면 아마 해당 커밋들이 안 보일 것 같습니다.

2023-10-21 15:02 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/main/model/repository/ArticleRepository.kt
> +    fun findAllByWriter(writer: User) : List<Article>
변경했습니다!

2023-10-22 12:47 UTC, kkanggu requested changes
확인 후 수정 혹은 코멘트 부탁드립니다.

2023-10-22 12:47 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/mypage/dto/response/MyScrapResponse.kt
> +)
내용(content)을 전부 노출하나요? 일부만 노출한다면 내용의 일부(size)만 보내주어도 될 것 같습니다.

2023-10-22 12:47 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/mypage/service/MypageService.kt
> +        }
이 경우 오름차순(과거 스크랩)으로 나올 것 같은데, 정렬 확인 부탁드립니다.

2023-10-30 06:51 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/mypage/dto/response/MyScrapResponse.kt
> +)
내용은 어느정도 보내주면 되나요?

2023-10-30 06:52 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/mypage/service/MypageService.kt
> +        }
넵 밑에 내가 쓴 게시글도 정렬하겠습니다

2023-10-30 14:10 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/mypage/dto/response/MyScrapResponse.kt
> +)
이 부분은 프론트측에 문의하는게 더욱 정확할 것 같습니다. 프리뷰라고 보시면 되는데, 렌더링 간격에 따라 size가 다를 수 있기에 이 부분도 같이 문의하면 좋을 것 같습니다.

2023-11-06 02:47 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/mypage/service/MypageService.kt
> +        }
수정했습니다

2023-11-22 01:30 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/mypage/dto/response/MyScrapResponse.kt
> +)
프론트에서 짜르신다고 그대로 진행하라고 하시네요.

2023-11-22 10:56 UTC, closed without merging

2023-11-22 11:40 UTC, swdevsw98 commented
제가 방법을 잘못알고 있었던거 같아서 #80 이후에 pr 올리겠습니다.