[#75] 닉네임 변경
DaITssu/daitssu-api pull request #89
Opened 2023-11-06 05:41 UTC by JooHui-void

## Issue

- Resolves #75 

## Description

- 닉네임 변경 관련 service, controller, test 추가 

## Check List

- [ ]  PR 제목을 커밋 규칙에 맞게 작성
- [ ]  PR에 해당되는 Issue를 연결 완료
- [ ]  적절한 라벨 설정
- [ ]  작업한 사람 모두를 Assign
- [ ]  작업한 팀에게 Code Review 요청 (Reviewer 등록)
- [ ]  `main` 브랜치의 최신 상태를 반영하고 있는지 확인

## Screenshot

2023-11-06 14:10 UTC, kkanggu requested changes
리뷰드린 내용만 수정하면 바로 Merge해도 될 것 같습니다.

2023-11-06 14:10 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/main/controller/UserController.kt
> +        Response(data = userService.updateNickname(userId = userId, nickname = nickname))
User의 일부(Nickname)만 바꾸는 작업인데, PUT이 목적에 맞는지 모르겠습니다.

2023-11-06 14:10 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/main/service/UserService.kt
> +import jakarta.transaction.Transactional
보통 `springframework`의 `Transactional`을 사용하는데, `jakarta`의 `Transactional`을 쓰는 이유가 뭘까요?

2023-11-06 14:10 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/main/service/UserService.kt
> +        userRepository.save(user)
```
val user = (userRepository.findByIdOrNull(userId)?.also {
    it.nickname = nickname
}?.also {
    userRepository.save(it)
} ?: throw DefaultException(errorCode = ErrorCode.USER_NOT_FOUND, httpStatus = HttpStatus.NOT_FOUND))
```
처럼 변경하면 더욱 Kotlin 스타일이 될 것 같습니다.

2023-11-06 14:10 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/main/service/UserService.kt
> +            nickname = user.nickname?: throw DefaultException(errorCode = ErrorCode.USER_NICKNAME_MISSING),
`nickname`을 null이 아닌 값으로 변경하였는데, null이 되는 경우가 있을까요?

2023-11-06 14:10 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/main/service/UserService.kt
> +    }
변경이라는 행위를 목적으로 하는 API인데, User에 대한 정보를 넘겨주는 이유가 있을까요?

2023-11-06 14:10 UTC, kkanggu commented on src/test/kotlin/com/example/daitssuapi/domain/main/controller/UserControllerTest.kt
> +    @DisplayName("userId를 이욯하여 닉네임 변경")
오타가 있습니다.

2023-11-07 02:32 UTC, JooHui-void commented on src/main/kotlin/com/example/daitssuapi/domain/main/controller/UserController.kt
> +        Response(data = userService.updateNickname(userId = userId, nickname = nickname))
PatchMapping으로 변경하겠습니다!

2023-11-07 03:59 UTC, JooHui-void commented on src/main/kotlin/com/example/daitssuapi/domain/main/service/UserService.kt
> +        userRepository.save(user)
한구님 알려주신 부분을 알아봤는데 also를 사용하면 user 데이터 변경이 이루어지지 않아서 UserResponse를 리턴할 때 변경 전 닉네임이 들어가는 듯 합니다
이부분이 상관이 없을까요 아니면 apply를 사용해서 적용해볼까요??

2023-11-07 04:12 UTC, JooHui-void commented on src/main/kotlin/com/example/daitssuapi/domain/main/service/UserService.kt
> +    }
그러네요..? 이 상황이면 변경 후의 nickname만 리턴하는것이 바람직할까요? 우선 이 방식으로 변경해두겠습니다!

2023-11-07 14:37 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/main/service/UserService.kt
> +        userRepository.save(user)
어... 그거까진 확인해보지 못했는데, apply도 좋은 접근이네요. 정 안되면 기존 소스처럼 풀어서 사용해도 괜찮을 것 같습니다.

2023-11-07 14:39 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/main/service/UserService.kt
> +    }
예외가 발생하면 해당 정보가 알아서 반환되기에 정상적인 흐름에서는 항상 닉네임이 바뀔 것 같습니다. 따라서 항상 `Response<Nothing>` 및 200으로 간단히 넘기거나, 말씀하신 것처럼 적용된 nickname을 넘겨줘도 될 것 같습니다. 추후 닉네임 필터링이나 중복 이슈 등이 생길 수 있기에, 변경된 닉네임을 넘겨주는 방향이 확장성이 좋을 것 같습니다.

2023-11-08 00:43 UTC, JooHui-void commented on src/main/kotlin/com/example/daitssuapi/domain/main/service/UserService.kt
> +    }
넵 감사합니다!!!!

2023-11-11 09:08 UTC, kkanggu approved these changes
병합 이전에 Swagger만 작업하시고 알아서 merge 부탁드립니다. 고생하셨습니다.

2023-11-11 09:08 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/main/controller/UserController.kt
> +    @PatchMapping("/nickname")
Swagger가 빠져있네요.

2023-11-12 05:25 UTC, JooHui-void commented on src/main/kotlin/com/example/daitssuapi/domain/main/controller/UserController.kt
> +    @PatchMapping("/nickname")
감사합니다!

2023-11-12 06:00 UTC, merged