[#1] 강의 정보 조회
DaITssu/daitssu-api pull request #9
Opened 2023-07-19 07:03 UTC by swdevsw98

## Issue

- Resolves #1 

## Description

- 강의 리스트 조회
- 강의 단일 조회

2023-07-21 00:46 UTC, kkanggu commented
컨벤션이 아직 픽스되지 않은 상황이라, 이후 컨벤션 확정 이후에 Merge 진행하셔야할 것 같습니다

2023-07-21 00:47 UTC, kkanggu requested changes
컨벤션이 아직 픽스되지 않은 상황이라, 이후 컨벤션 확정 이후에 Merge 진행하셔야할 것 같습니다

2023-07-21 00:47 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +    @GetMapping("")
`@GetMapping` 만 이용하는건 어떠신가요

2023-07-21 00:47 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +        date: String
이렇게 되면 컨트롤러에서 입력 포맷 검증 + API 수정이 어려워지지 않을까요?
그리고 여기서 에러가 나면 어떻게 될까요?

2023-07-21 00:47 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        }
하나씩 Iteration 돌지 않고 바로 넣는 방법은 없을까요?

2023-07-21 00:47 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        val date = LocalDateTime.parse(date, formatter)
2023-02-30, 2023-05-31과 같은 잘못된 날짜가 들어가면 어떻게 되나요?

2023-07-21 00:47 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        }
처음부터 requestType을 Enum으로 받을 방법은 없을까요?

2023-07-21 00:47 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        val vd = Video(LocalDateTime.now().plusDays(7), LocalDateTime.now(), name, course)
Video의 Field를 보지 않으면 7일을 더하는 의도를 파악할 수 있을까요?

2023-07-21 04:28 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +    @GetMapping("")
수정했습니다

2023-07-21 04:46 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +        date: String
캘린더로 선택하는 형식이여서 고정했는데 그러면 그냥 스트링으로 받아서 변경하겠습니다

2023-07-21 04:57 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        val vd = Video(LocalDateTime.now().plusDays(7), LocalDateTime.now(), name, course)
그 마감기한 설정 기준을 몰라서 임의로 강의를 추가할때 등록시간 +7일했습니다

2023-07-21 05:05 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        }
수정했습니다

2023-07-21 05:23 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        }
수정했습니다

2023-07-21 05:28 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        val date = LocalDateTime.parse(date, formatter)
500 파싱에러가 납니다 수정하기 좋은 방향이 있을까요?

2023-07-21 05:50 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/controller/CourseController.kt
> +        date: String
포맷이 안맞으면 "Invalid date format. Date should be in 'yyyy-MM-dd HH:mm:ss' format." 에러가 나게 수정했습니다

2023-07-21 12:34 UTC, kkanggu commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        val date = LocalDateTime.parse(date, formatter)
500은 외부에서 바라볼 때의 응답이지만, 내부에서 500이 발생하게 된 원인을 확인해보시는게 좋을 것 같습니다.

2023-07-23 04:43 UTC, swdevsw98 commented on test/src/main/kotlin/com/example/test/domain/course/service/CourseService.kt
> +        val date = LocalDateTime.parse(date, formatter)
위에 처럼  "Invalid date format. Date should be in 'yyyy-MM-dd HH:mm:ss' format."  에러 내겠습니다

2023-07-24 06:45 UTC, HwanGonJang reviewed
잘 작성해주신 것 같아요! 우선 한구님 베이스 컨벤션 pr병합되면 리뷰 반영해주시고 병합하는 걸로 하시죵

2023-08-09 06:18 UTC, swdevsw98 commented
리팩토링은 #2에서 진행했습니다

2023-08-09 06:19 UTC, closed without merging