[#61] user_id 추가 및 일정에서 user 핸들링하기
DaITssu/daitssu-api pull request #91
Opened 2023-11-09 04:43 UTC by swdevsw98

## Issue

- Resolves #61 

## Description

- userId 추가해서 calendar 핸들링

## Check List

- [ ]  PR 제목을 커밋 규칙에 맞게 작성
- [ ]  PR에 해당되는 Issue를 연결 완료
- [ ]  적절한 라벨 설정
- [ ]  작업한 사람 모두를 Assign
- [ ]  작업한 팀에게 Code Review 요청 (Reviewer 등록)
- [ ]  `main` 브랜치의 최신 상태를 반영하고 있는지 확인

## Screenshot

2023-11-11 09:12 UTC, kkanggu requested changes
리뷰 확인하시고 수정 부탁드립니다.

2023-11-11 09:12 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/course/controller/CourseController.kt
>      ): Response<Map<String, List<CalendarResponse>>> =
course 관련 URL에 갑자기 userId가 Path로 나오는게 부자연스러운 것 같습니다.
추가적으로, 그때는 못 본 것 같은데 date가 path로 가는 것 또한 적절하지 않은 것 같습니다.

2023-11-11 09:12 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/course/controller/CourseController.kt
> +        Response(data = courseService.getTodayDueAtCalendars(userId = userId))
userId는 위와 동일합니다. 또한 URL에 today가 들어가는게 적절한 방식인지 모르겠습니다.

2023-11-11 09:12 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/course/model/repository/CalendarRepository.kt
>          startDateTime: LocalDateTime,
이 3개의 Query는 모두 userId가 필수인데요. 해당 Query를 사용하는 기능들은 모두 userId가 필수인 기능인가요?

2023-11-11 14:19 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/course/controller/CourseController.kt
>      ): Response<Map<String, List<CalendarResponse>>> =
@RequestParam으로 변경하면 될까요? get방식이라 body로는 안되는걸로 알고 있어서요!

2023-11-11 14:20 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/course/controller/CourseController.kt
> +        Response(data = courseService.getTodayDueAtCalendars(userId = userId))
today를 더 적절한 명사로 바꾸라는 말씀일까요?

2023-11-11 14:33 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/course/model/repository/CalendarRepository.kt
>          startDateTime: LocalDateTime,
넵 피그마로 봤을땐 캘린더에 직접 추가한 내용이라 userId가 있어야할꺼 같습니다.

2023-11-27 12:23 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/course/controller/CourseController.kt
>      ): Response<Map<String, List<CalendarResponse>>> =
두가지 모두 RequestParam이 더 적절해보입니다.

2023-11-27 12:25 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/course/controller/CourseController.kt
> +        Response(data = courseService.getTodayDueAtCalendars(userId = userId))
URL 디자인에 resource가 아닌게 path로 들어가는게 많이 부자연스럽습니다. today라는 내용이 꼭 필요하다면 https://cloud.google.com/apis/design/custom_methods?hl=ko와 같이 Custom하게 변경하는게 더 나은 것 같습니다.

2023-12-09 06:12 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/course/controller/CourseController.kt
> +        Response(data = courseService.getTodayDueAtCalendars(userId = userId))
due-today로 수정할까 하는데 괜찮을까요?

2023-12-10 13:49 UTC, kkanggu commented
userId 토큰으로 받아오도록 수정이 필요하기에 기존 PR Close

2023-12-10 13:49 UTC, closed without merging