[#80] 내가 쓴 글 조회
DaITssu/daitssu-api pull request #96
Opened 2023-11-22 10:53 UTC by swdevsw98

## Issue

- Resolves #80 

## Description

- develop conflict 해결
- controller test에서 401 에러는 아직 발생

## Check List

- [ ]  PR 제목을 커밋 규칙에 맞게 작성
- [ ]  PR에 해당되는 Issue를 연결 완료
- [ ]  적절한 라벨 설정
- [ ]  작업한 사람 모두를 Assign
- [ ]  작업한 팀에게 Code Review 요청 (Reviewer 등록)
- [ ]  `main` 브랜치의 최신 상태를 반영하고 있는지 확인

## Screenshot

2023-11-27 13:19 UTC, kkanggu requested changes
현재 작업하지 않은 부분으로 인해 테스트 Build도 되지 않고 있습니다. 해당 부분도 확인하셔서 수정 부탁드립니다. TODO로 남기고 해당 테스트를 Disable하거나 주석 처리 하여도 괜찮습니다.

2023-11-27 13:19 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/mypage/controller/MypageController.kt
> +}
`package com.example.daitssuapi.domain.main.controller` 가 이미 존재하는데, postgres에 맞춘 경로였습니다. 현재 작업하신 패키지로 이전해야할 것 같은데, 기존 Controller에 Deprecated 추가 부탁드립니다.

2023-11-27 13:19 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/mypage/service/MypageService.kt
> +                commentSize = commentRepository.findByArticleId(it.id).size
Article에 comments로 이미 참조하고 있습니다. 또한 isDeleted로 노출 여부를 결정하니 해당 필터도 추가해야할 것 같습니다.

2023-11-27 13:19 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/mypage/service/MypageService.kt
> +        }.sortedByDescending { it.createdAt }
동일한 결과를 가져오겠으나, Response로 변환 이후 정렬 / 정렬 후 Response로 변환 두 가지 방법이 존재합니다. 다만 현재 로직만 놓고 본다면 정렬을 먼저 하는게 적합하지 않을까- 싶습니다.

2023-11-27 13:19 UTC, kkanggu commented on src/test/kotlin/com/example/daitssuapi/domain/mypage/controller/MypageControllerTest.kt
> +    }
1개 이상의 게시글이 조회되는 것을 테스트하나, 실제로 데이터가 존재하는지 검증을 하지 않고 있습니다.

2023-11-27 13:19 UTC, kkanggu commented on src/test/kotlin/com/example/daitssuapi/domain/mypage/service/MypageServiceTest.kt
> +        )
기존 SQL이 변화하면 해당 테스트는 깨질 가능성이 높습니다. Index를 이용하여 저런 방식으로 테스트하면 당장은 잘 돌아가도, 추후 유지보수가 어려워집니다.

2023-11-27 13:19 UTC, HwanGonJang approved these changes

2023-11-27 13:21 UTC, kkanggu commented
추가로 jwt 추가로 인하여 Controller Test가 전부 401이 뜨고 있습니다. 이 부분은 @HwanGonJang 님이 확인하셔야할 것 같습니다.

2023-11-29 10:41 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/mypage/controller/MypageController.kt
> +}
`package com.example.daitssuapi.domain.main.controller` 이 컨트롤러에 @Deprecated 붙여달라는 말씀일까요?

2023-11-29 10:58 UTC, swdevsw98 commented
혹시 저는 테스트 실행이 되서 어떤 이유로 빌드가 안되는지 알 수 있을까요? 작업하지 않은게 뭔지 모르겠습니다

2023-11-29 11:53 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/mypage/service/MypageService.kt
> +                commentSize = commentRepository.findByArticleId(it.id).size
수정했습니다

2023-11-29 11:53 UTC, swdevsw98 commented on src/main/kotlin/com/example/daitssuapi/domain/mypage/service/MypageService.kt
> +        }.sortedByDescending { it.createdAt }
수정했습니다

2023-11-29 11:53 UTC, swdevsw98 commented on src/test/kotlin/com/example/daitssuapi/domain/mypage/controller/MypageControllerTest.kt
> +    }
수정했습니다

2023-11-29 11:53 UTC, swdevsw98 commented on src/test/kotlin/com/example/daitssuapi/domain/mypage/service/MypageServiceTest.kt
> +        )
수정했습니다

2023-12-01 15:33 UTC, kkanggu approved these changes
Unit Test만 삭제하시면 병합해도 될 것 같습니다. 고생하셨습니다.

2023-12-01 15:33 UTC, kkanggu commented on src/test/kotlin/com/example/daitssuapi/unit/domain/mypage/service/MyPageServiceUnitTest.kt
> +class MyPageServiceUnitTest {
외부 의존성이 없으며, 전부 간단한 API로 구성되어 있기에 Unit Test가 현재는 사실상 무의미합니다. 깔끔하게 Unit Test 전부 제거하는 방향이 좋을 것 같아, 해당 테스트도 아예 삭제 부탁드립니다.

2023-12-01 15:33 UTC, kkanggu commented on src/main/kotlin/com/example/daitssuapi/domain/mypage/controller/MypageController.kt
> +}
네 맞습니다

2023-12-02 03:45 UTC, swdevsw98 commented on src/test/kotlin/com/example/daitssuapi/unit/domain/mypage/service/MyPageServiceUnitTest.kt
> +class MyPageServiceUnitTest {
수정했습니다. 병합하겠습니다.

2023-12-02 03:45 UTC, merged